// ─── Encyclopédie Dinosaures MaxPlay ───
// 60 dinos · données riches · FR · adapté 3-5 ans
// Catégories : carnivores · herbivores · piscivores · omnivores · volants_marins

// ─── Familles (2e catégorisation) ───
const DINO_FAMILLES = [
  { id: 'trex',       label: 'Les T-Rex',         emoji: '🦖', desc: 'Les grands chasseurs à deux pattes',      color: '#c0392b', bg: 'linear-gradient(135deg,#7b0000,#c0392b)' },
  { id: 'cou_long',   label: 'Les Cou-longs',     emoji: '🦕', desc: 'Les géants au très long cou',             color: '#27ae60', bg: 'linear-gradient(135deg,#0a4a1e,#27ae60)' },
  { id: 'arme',       label: 'Les Tout-blindés',  emoji: '🛡️', desc: 'Armure, piques et queue-massue',         color: '#7f8c8d', bg: 'linear-gradient(135deg,#2c3e50,#7f8c8d)' },
  { id: 'cornu',      label: 'Les Cornus',        emoji: '🦏', desc: 'Cornes, crêtes et grandes collerettes',   color: '#f39c12', bg: 'linear-gradient(135deg,#7a5000,#f39c12)' },
  { id: 'bec',        label: 'Les Becs-de-canard',emoji: '🦆', desc: 'Bec plat, crête et grands troupeaux',     color: '#8e44ad', bg: 'linear-gradient(135deg,#4a0080,#8e44ad)' },
  { id: 'raptor',     label: 'Les Raptors',       emoji: '🦅', desc: 'Griffes mortelles et chasseurs malins',   color: '#e67e22', bg: 'linear-gradient(135deg,#7a3000,#e67e22)' },
  { id: 'volant',     label: 'Volants & Marins',  emoji: '🦋', desc: 'Dans les airs et les mers préhistoriques',color: '#2980b9', bg: 'linear-gradient(135deg,#003366,#2980b9)' },
  { id: 'bizarre',    label: 'Les Bizarres',      emoji: '🤪', desc: 'Inclassables et super originaux !',        color: '#16a085', bg: 'linear-gradient(135deg,#0a3d30,#16a085)' },
];

// ─── La Pangée (intro chronomap) ───
const PANGEE = {
  titre: 'La Pangée',
  soustitre: 'Quand tous les continents étaient collés !',
  emoji: '🌍',
  intro: 'Avant les dinosaures, tous les continents de la Terre étaient collés ensemble en un seul morceau géant ! On l\'appelle la Pangée. On pouvait marcher de l\'Afrique jusqu\'en Amérique à pied, sans bateau !',
  credit: 'Cartes : C. Scotese / PALEOMAP — Wikimedia Commons, CC BY 4.0',
  etapes: [
    {
      periode: 'trias',
      label: 'Trias',
      ma: 'il y a 250 millions d\'années',
      titre: 'Tout est collé',
      texte: 'Au temps des premiers dinosaures, toute la terre formait un seul super-continent : la Pangée. Il faisait très chaud et très sec partout.',
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Mollweide_Paleographic_Map_of_Earth%2C_250_Ma_%28Olenekian_Age%29.png/960px-Mollweide_Paleographic_Map_of_Earth%2C_250_Ma_%28Olenekian_Age%29.png',
    },
    {
      periode: 'jurassique',
      label: 'Jurassique',
      ma: 'il y a 155 millions d\'années',
      titre: 'Ça commence à se fendre',
      texte: 'La Pangée se casse lentement en deux gros morceaux. Un grand océan s\'ouvre au milieu. Les dinosaures des deux côtés ne se voient plus !',
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Mollweide_Paleographic_Map_of_Earth%2C_155_Ma_%28Oxfordian_Age%29.png/960px-Mollweide_Paleographic_Map_of_Earth%2C_155_Ma_%28Oxfordian_Age%29.png',
    },
    {
      periode: 'cretace',
      label: 'Crétacé',
      ma: 'il y a 85 millions d\'années',
      titre: 'Ça s\'écarte',
      texte: 'Les continents continuent de glisser tout doucement, comme des radeaux géants. Ça commence à ressembler à la Terre d\'aujourd\'hui !',
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Mollweide_Paleographic_Map_of_Earth%2C_85_Ma_%28Santonian_Age%29.png/960px-Mollweide_Paleographic_Map_of_Earth%2C_85_Ma_%28Santonian_Age%29.png',
    },
    {
      periode: 'present',
      label: 'Aujourd\'hui',
      ma: 'maintenant',
      titre: 'La Terre qu\'on connaît',
      texte: 'Après des millions d\'années, les continents sont arrivés là où ils sont aujourd\'hui. Et ils bougent encore… tout doucement !',
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Mollweide_Paleographic_Map_of_Earth%2C_5_Ma_%28Zanclean_Age%29.png/960px-Mollweide_Paleographic_Map_of_Earth%2C_5_Ma_%28Zanclean_Age%29.png',
    },
  ],
  fun_fact: 'Les continents bougent encore aujourd\'hui ! Mais très très lentement : à peine la vitesse à laquelle tes ongles poussent !',
  pourquoi: 'C\'est pour ça que le Cryolophosaure vivait en Antarctique : à l\'époque il y faisait chaud, et c\'était collé aux autres terres !',
};

// ─── Extinction (écran spécial après Crétacé) ───
const EXTINCTION = {
  titre: 'La Grande Extinction',
  soustitre: 'Il y a 66 millions d\'années…',
  emoji: '☄️',
  hypotheses: [
    {
      id: 'meteorite',
      emoji: '☄️',
      titre: 'La météorite géante',
      texte: 'Un rocher de 10 km venu du ciel s\'écrase dans le Mexique actuel. L\'explosion est 10 milliards de fois plus puissante qu\'une bombe atomique. Tout brûle dans un rayon de milliers de kilomètres. C\'est la théorie la plus probable !',
      certitude: '⭐⭐⭐⭐⭐',
      label_certitude: 'Très probable',
    },
    {
      id: 'volcan',
      emoji: '🌋',
      titre: 'Les super-volcans',
      texte: 'En Inde, des volcans gigantesques crachent des laves et des gaz pendant des milliers d\'années. La fumée empoisonne l\'air et réchauffe la Terre. Les volcans Dekkan ont recouvert la moitié de l\'Inde de lave !',
      certitude: '⭐⭐⭐⭐',
      label_certitude: 'Très plausible',
    },
    {
      id: 'cendres',
      emoji: '🌑',
      titre: 'Le nuage de cendres',
      texte: 'Après le choc de la météorite, un nuage de poussière et de cendres cache le soleil pendant des mois… peut-être des années ! Sans soleil, les plantes meurent. Sans plantes, les herbivores meurent. Sans herbivores, les carnivores meurent.',
      certitude: '⭐⭐⭐⭐⭐',
      label_certitude: 'Presque certain',
    },
    {
      id: 'froid',
      emoji: '🥶',
      titre: 'L\'hiver nucléaire',
      texte: 'La Terre plonge dans le noir et le froid. La température chute de 10 à 20 degrés partout sur Terre. Les plantes tropicales meurent. Les océans refroidissent. C\'est un hiver qui dure des années !',
      certitude: '⭐⭐⭐⭐',
      label_certitude: 'Très probable',
    },
    {
      id: 'survivants',
      emoji: '🐦',
      titre: 'Et les survivants ?',
      texte: 'Les petits animaux qui mangeaient des graines et pouvaient se cacher survivent. Les oiseaux — qui sont de vrais dinosaures ! — passent à travers. Les crocodiles, les tortues, les lézards résistent. La vie repart… et des millions d\'années plus tard, les humains arrivent !',
      certitude: null,
      label_certitude: null,
    },
  ],
  fun_fact: 'Les oiseaux sont de VRAIS dinosaures ! Chaque fois que Max voit un pigeon, il voit un dino !',
};


const DINO_CATEGORIES = [
  { id: 'carnivores',     label: 'Carnivores',       emoji: '🥩', color: '#c0392b', bg: 'linear-gradient(135deg,#7b0000,#c0392b)' },
  { id: 'herbivores',     label: 'Herbivores',       emoji: '🌿', color: '#27ae60', bg: 'linear-gradient(135deg,#0a4a1e,#27ae60)' },
  { id: 'piscivores',     label: 'Piscivores',       emoji: '🐟', color: '#2980b9', bg: 'linear-gradient(135deg,#003366,#2980b9)' },
  { id: 'omnivores',      label: 'Omnivores',        emoji: '🍃', color: '#e67e22', bg: 'linear-gradient(135deg,#7a3000,#e67e22)' },
  { id: 'volants_marins', label: 'Volants & Marins', emoji: '🌊', color: '#8e44ad', bg: 'linear-gradient(135deg,#4a0080,#8e44ad)' },
];

const DINO_CONTINENTS = [
  { id: 'Amérique du Nord', label: 'Amérique du Nord', emoji: '🌎', color: '#e74c3c', bg: 'linear-gradient(135deg,#7b1010,#e74c3c)' },
  { id: 'Amérique du Sud', label: 'Amérique du Sud',  emoji: '🌎', color: '#e67e22', bg: 'linear-gradient(135deg,#7a3000,#e67e22)' },
  { id: 'Europe',           label: 'Europe',           emoji: '🌍', color: '#3498db', bg: 'linear-gradient(135deg,#003366,#3498db)' },
  { id: 'Afrique',          label: 'Afrique',          emoji: '🌍', color: '#f39c12', bg: 'linear-gradient(135deg,#7a5000,#f39c12)' },
  { id: 'Asie',             label: 'Asie',             emoji: '🌏', color: '#e91e63', bg: 'linear-gradient(135deg,#7b003a,#e91e63)' },
  { id: 'Antarctique',      label: 'Antarctique',      emoji: '🧊', color: '#00bcd4', bg: 'linear-gradient(135deg,#003344,#00bcd4)' },
];

const DINO_PERIODES = [
  {
    id: 'permien',
    label: 'Permien',
    emoji: '🌋',
    range: '280 Ma',
    desc: 'Avant les dinosaures',
    ma_start: 280, ma_end: 252,
    color: '#795548',
    bg: 'linear-gradient(135deg,#3e2723,#795548)',
  },
  {
    id: 'trias',
    label: 'Trias',
    emoji: '🌿',
    range: '252 – 201 Ma',
    desc: 'Les premiers dinosaures',
    ma_start: 252, ma_end: 201,
    color: '#ff7043',
    bg: 'linear-gradient(135deg,#7a1a00,#ff7043)',
  },
  {
    id: 'jurassique',
    label: 'Jurassique',
    emoji: '🦕',
    range: '201 – 145 Ma',
    desc: 'Les géants sauropodes',
    ma_start: 201, ma_end: 145,
    color: '#66bb6a',
    bg: 'linear-gradient(135deg,#1b5e20,#66bb6a)',
  },
  {
    id: 'cretace',
    label: 'Crétacé',
    emoji: '🦖',
    range: '145 – 66 Ma',
    desc: 'Le règne du T-Rex',
    ma_start: 145, ma_end: 66,
    color: '#42a5f5',
    bg: 'linear-gradient(135deg,#0d2a66,#42a5f5)',
  },
];

// ─── Comparaisons taille / poids (référentiel Max validé 2026-05-16) ───
// Référentiels : Papa = 1,8 m · vélo = 1,7 m · voiture = 4 m · bus = 12 m ·
//                bus anglais 2 étages ≈ 4,4 m haut · étage immeuble = 3 m ·
//                éléphant = 5 t · hippopotame = 3 t · rhinocéros = 1 t ·
//                grand chien = 30 kg · chat = 4 kg.
// Les fonctions renvoient une comparaison SANS le chiffre (le chiffre exact
// est affiché dans les stats et dit séparément par la lecture vocale).
function _round1(x) { return Math.round(x * 10) / 10; }

// ─── Échelle de référence figée 2026-06-01 (voir docs/jeux/dino-encyclopedie/_ECHELLE-REFERENTIEL.md) ───
// Repères : Papa 1,8 m · enfant 4 ans 1 m · voiture 1,5 m haut · porte 2 m · but de foot 2,44 m ·
// panier de basket 3,05 m · bus anglais 4,4 m · lampadaire 6 m · étage 3 m · bus RATP 12 m · accordéon 18 m.
// Règle : jamais un arrondi qui ment de plus de ~10 %.
function _qty(n, sing, plur) { return n <= 1 ? `un ${sing}` : `${n} ${plur}`; }

// LONGUEUR (nez → bout de la queue, allongé / garé). Objet familier d'abord.
function _compLong(m) {
  if (m >= 30)  return `comme un bus accordéon et un bus, l'un derrière l'autre !`;
  if (m >= 24)  return `comme deux bus l'un derrière l'autre !`;
  if (m >= 16)  return `aussi long qu'un bus accordéon !`;
  if (m >= 11)  return `aussi long qu'un bus RATP !`;
  if (m >= 8.5) return `aussi long qu'un camion !`;
  if (m >= 7)   return `comme deux voitures l'une derrière l'autre !`;
  if (m >= 5.6) return `aussi long qu'une rue à deux voies est large — il barrait la route !`;
  if (m >= 4.3) return `aussi long qu'un grand 4×4 !`;
  if (m >= 3.3) return `comme une petite voiture !`;
  if (m >= 2.4) return `comme trois enfants de 4 ans allongés !`;
  if (m >= 1.9) return `aussi long qu'une moto !`;
  if (m >= 1.7) return `comme un grand Papa allongé par terre !`;
  if (m >= 1.35) return `aussi long qu'un vélo !`;
  if (m >= 0.8) return `comme un grand chien — un labrador !`;
  if (m >= 0.45) return `comme un gros chat allongé !`;
  return `tout petit, comme un poulet !`;
}

// HAUTEUR (sol → tête, debout). Bipède = hanche ; quadrupède = épaule ; cou vertical = tête.
function _compHaut(m) {
  if (m >= 11)  return `aussi haut qu'un immeuble de ${Math.round(m / 3)} étages !`;
  if (m >= 7.5) return `aussi haut qu'un immeuble de trois étages !`;
  if (m >= 5.6) return `aussi haut qu'un lampadaire !`;
  if (m >= 4.8) return `presque trois Papas l'un sur l'autre !`;
  if (m >= 4.0) return `aussi haut qu'un bus anglais à deux étages !`;
  if (m >= 3.3) return `comme deux Papas l'un sur l'autre !`;
  if (m >= 2.8) return `aussi haut qu'un panier de basket !`;
  if (m >= 2.3) return `aussi haut qu'un but de foot !`;
  if (m >= 2.1) return `comme Papa qui te porte tout en haut sur ses épaules !`;
  if (m >= 1.9) return `aussi haut qu'une porte !`;
  if (m >= 1.7) return `aussi grand que Papa debout !`;
  if (m >= 1.25) return `aussi haut qu'une voiture — il fallait lever la tête !`;
  if (m >= 0.85) return `aussi grand qu'un enfant de 4 ans !`;
  if (m >= 0.65) return `il t'arrivait au nombril !`;
  if (m >= 0.45) return `il t'arrivait aux fesses !`;
  if (m >= 0.25) return `il t'arrivait aux genoux !`;
  return `plus bas que tes genoux !`;
}

// POIDS (t). Repères : chat 4 kg · enfant 4 ans 16 kg · gros chien 30 kg · enfant 10 ans 50 kg ·
// Papa 80 kg · gros cochon 200 kg · vache 0,7 t · rhino 1,5 t · hippo 3 t · éléphant 6 t.
function _compPoids(t) {
  if (t >= 11)   return `aussi lourd que ${_qty(Math.round(t / 6), 'éléphant', 'éléphants')} !`;
  if (t >= 4)    return `aussi lourd que ${_qty(Math.round(t / 3), 'hippopotame', 'hippopotames')} !`;
  if (t >= 2)    return `aussi lourd que ${_qty(Math.round(t / 1.5), 'rhinocéros', 'rhinocéros')} !`;
  if (t >= 1.2)  return `aussi lourd qu'un rhinocéros !`;
  if (t >= 0.5)  return `aussi lourd qu'une vache !`;
  if (t >= 0.13) return `aussi lourd qu'un gros cochon !`;
  if (t >= 0.065) return `aussi lourd que Papa !`;
  if (t >= 0.04) return `aussi lourd qu'un grand enfant de 10 ans !`;
  if (t >= 0.022) return `aussi lourd qu'un gros chien !`;
  if (t >= 0.011) return `aussi lourd qu'un enfant de 4 ans !`;
  if (t >= 0.0035) return `aussi lourd qu'un gros chat !`;
  return `léger comme un petit oiseau !`;
}

// Texte lecture vocale des 3 mesures (m + kg + comparaison)
// fr() : virgule décimale pour que le TTS dise "un virgule huit" pas "un point huit"
function _fr(n) { return String(n).replace('.', ' virgule '); }
function _statsPhrase(d) {
  const kg = d.poids_t >= 1
    ? Math.round(d.poids_t) + ' mille kilos'
    : Math.round(d.poids_t * 1000) + ' kilos';
  const lng = d.taille_vol
    ? `Il avait des ailes de ${_fr(d.taille_m)} mètres d'un bout à l'autre — ${d.comp_taille}`
    : `Il mesurait ${_fr(d.taille_m)} mètres de long — ${d.comp_taille}`;
  return `${lng} ${d.hauteur_m ? `Debout, il faisait ${_fr(d.hauteur_m)} mètres de haut — ${d.comp_hauteur} ` : ''}Et il pesait ${kg} — ${d.comp_poids}`;
}

const DINOS = [

  // ══════════════ 1. LES CHASSEURS ══════════════

  {
    id: 'tyrannosaurus',
    name: 'T-Rex',
    full: 'Tyrannosaurus Rex',
    famille: 'trex',
    cat: 'carnivores',
    epoque: 'Crétacé · il y a 66 millions d\'ans',
    region: 'Amérique du Nord',
    taille_m: 12,
    hauteur_m: 4,
    poids_t: 8,
    comp_taille: _compLong(12),
    comp_hauteur: _compHaut(4),
    comp_poids: _compPoids(8),
    nom_etym: 'Son nom veut dire «lézard tyran» en grec — c\'est le lézard qui commande tout le monde !',
    regime: '🥩 Carnivore',
    superpower: 'La morsure la plus puissante de tous les dinos terrestres !',
    chasseurs: 'Personne n\'osait l\'attaquer... il était le roi !',
    proies: 'Triceratops, Edmontosaurus, Ankylosaure',
    amis: 'Plutôt solitaire, mais peut-être en famille parfois',
    fait: 'Ses dents mesuraient 20 cm — plus longues que ta main ! Et il en avait 60 !',
    desc: 'Le T-Rex est le roi des dinosaures. Il avait une tête énorme, des dents géantes, et des bras tout petits. Mais attention, ses pattes arrière couraient très vite !',
    png: 'Tyrannosaurus.png',
    color: '#c0392b',
    continent: 'Amérique du Nord',
    periode: 'cretace',
  },
  {
    id: 'spinosaurus',
    famille: 'trex',
    name: 'Spinosaure',
    full: 'Spinosaurus aegyptiacus',
    cat: 'piscivores',
    epoque: 'Crétacé · il y a 95 millions d\'ans',
    region: 'Afrique du Nord',
    taille_m: 15,
    hauteur_m: 4,
    poids_t: 7,
    comp_taille: _compLong(15),
    comp_hauteur: _compHaut(4),
    comp_poids: _compPoids(7),
    nom_etym: 'Son nom veut dire «lézard à épines» en latin — il avait une grande voile sur le dos !',
    regime: '🐟 Piscivore (mange du poisson !)',
    superpower: 'Nager comme un crocodile géant ! Il adorait l\'eau.',
    chasseurs: 'Personne n\'osait s\'y frotter',
    proies: 'Gros poissons, requins préhistoriques',
    amis: 'Solitaire',
    fait: 'La voile sur son dos pouvait faire 2 mètres de haut — comme une porte d\'entrée !',
    desc: 'Le Spinosaure était encore plus grand que le T-Rex ! Il vivait près des rivières et attrapait d\'énormes poissons. Il avait une grande voile rouge sur le dos.',
    png: 'Spinosaurus.png',
    color: '#2471a3',
    continent: 'Afrique',
    periode: 'cretace',
  },
  {
    id: 'giganotosaurus',
    famille: 'trex',
    name: 'Giganotosaure',
    full: 'Giganotosaurus carolinii',
    cat: 'carnivores',
    epoque: 'Crétacé · il y a 98 millions d\'ans',
    region: 'Amérique du Sud',
    taille_m: 13,
    hauteur_m: 4,
    poids_t: 7,
    comp_taille: _compLong(13),
    comp_hauteur: _compHaut(4),
    comp_poids: _compPoids(7),
    nom_etym: 'Son nom veut dire «lézard géant du sud» en grec — il vivait très loin au sud !',
    regime: '🥩 Carnivore',
    superpower: 'Chassait en groupe pour attaquer les ÉNORMES sauropodes !',
    chasseurs: 'Aucun prédateur ne l\'attaquait',
    proies: 'Argentinosaurus (le plus grand dino !)',
    amis: 'Chassait peut-être en meutes, comme des lions',
    fait: 'C\'est le plus grand carnivore d\'Amérique du Sud ! Plus grand encore que le T-Rex !',
    desc: 'Le Giganotosaure vivait en Amérique du Sud. Il était ÉNORME et chassait peut-être en groupe pour attraper des dinosaures encore plus grands que lui !',
    png: 'Giganotosaurus.png',
    color: '#a93226',
    continent: 'Amérique du Sud',
    periode: 'cretace',
  },
  {
    id: 'carcharodontosaurus',
    famille: 'trex',
    name: 'Carcharodontosaure',
    full: 'Carcharodontosaurus saharicus',
    cat: 'carnivores',
    epoque: 'Crétacé · il y a 95 millions d\'ans',
    region: 'Afrique du Nord',
    taille_m: 13,
    hauteur_m: 3.8,
    poids_t: 7,
    comp_taille: _compLong(13),
    comp_hauteur: _compHaut(3.8),
    comp_poids: _compPoids(7),
    nom_etym: 'Son nom veut dire «lézard aux dents de requin» en grec — ses dents coupaient comme un requin !',
    regime: '🥩 Carnivore',
    superpower: 'Des dents en forme de dents de requin — couper comme un couteau !',
    chasseurs: 'Aucun dans son territoire',
    proies: 'Grands herbivores africains',
    amis: 'Solitaire',
    fait: 'Son nom veut dire "lézard aux dents de requin" ! Ses dents étaient dentelées comme une scie !',
    desc: 'Le Carcharodontosaure vivait en Afrique en même temps que le Spinosaure. Il avait des dents en forme de dents de requin pour découper sa nourriture.',
    png: 'Carcharodontosaurus.png',
    color: '#922b21',
    continent: 'Afrique',
    periode: 'cretace',
  },
  {
    id: 'acrocanthosaurus',
    famille: 'trex',
    name: 'Acrocanthosaure',
    full: 'Acrocanthosaurus atokensis',
    cat: 'carnivores',
    epoque: 'Crétacé · il y a 113 millions d\'ans',
    region: 'Amérique du Nord',
    taille_m: 11.5,
    hauteur_m: 3.5,
    poids_t: 6,
    comp_taille: _compLong(11.5),
    comp_hauteur: _compHaut(3.5),
    comp_poids: _compPoids(6),
    nom_etym: 'Son nom veut dire «lézard aux épines hautes» en grec — il avait des piques dans le dos !',
    regime: '🥩 Carnivore',
    superpower: 'Une crête de muscles sur tout le dos, comme un bison géant !',
    chasseurs: 'Aucun dans son époque',
    proies: 'Sauropodes géants (Astrodon...)',
    amis: 'Solitaire',
    fait: 'On a trouvé ses empreintes de pas en Texas ! Les traces font 60 cm de long !',
    desc: 'L\'Acrocanthosaure était le T-Rex de son époque. Il avait une grosse bosse de muscles sur le dos et chassait les dinosaures géants.',
    png: 'Acrocanthosaurus.png',
    color: '#8b1a1a',
    continent: 'Amérique du Nord',
    periode: 'cretace',
  },
  {
    id: 'allosaurus',
    famille: 'trex',
    name: 'Allosaure',
    full: 'Allosaurus fragilis',
    cat: 'carnivores',
    epoque: 'Jurassique · il y a 155 millions d\'ans',
    region: 'Amérique du Nord, Europe',
    taille_m: 9.5,
    hauteur_m: 3.5,
    poids_t: 2.3,
    comp_taille: _compLong(9.5),
    comp_hauteur: _compHaut(3.5),
    comp_poids: _compPoids(2.3),
    nom_etym: 'Son nom veut dire «lézard différent» en grec — ses os étaient différents de tous les autres !',
    regime: '🥩 Carnivore',
    superpower: 'Ouvrait sa gueule TRÈS grande comme une hache pour frapper !',
    chasseurs: 'Aucun de son époque n\'osait l\'affronter seul',
    proies: 'Stégosaure, Camarasaure, jeunes sauropodes',
    amis: 'Peut-être en groupe parfois',
    fait: 'Le T-Rex du Jurassique ! On a trouvé des centaines de ses os dans un seul endroit !',
    desc: 'L\'Allosaure était le super chasseur du Jurassique. Il ouvrait sa mâchoire très grande pour frapper sa proie comme un coup de hache !',
    png: 'Allosaurus.png',
    color: '#b03a2e',
    continent: 'Amérique du Nord',
    periode: 'jurassique',
  },
  {
    id: 'tarbosaurus',
    famille: 'trex',
    name: 'Tarbosaure',
    full: 'Tarbosaurus bataar',
    cat: 'carnivores',
    epoque: 'Crétacé · il y a 70 millions d\'ans',
    region: 'Asie (Mongolie)',
    taille_m: 10,
    hauteur_m: 4,
    poids_t: 5,
    comp_taille: _compLong(10),
    comp_hauteur: _compHaut(4),
    comp_poids: _compPoids(5),
    nom_etym: 'Son nom veut dire «lézard qui fait peur» en grec — tout le monde avait peur de lui !',
    regime: '🥩 Carnivore',
    superpower: 'Le T-Rex d\'Asie — cousin direct !',
    chasseurs: 'Aucun dans son territoire',
    proies: 'Grands herbivores d\'Asie',
    amis: 'Solitaire',
    fait: 'C\'est le cousin asiatique du T-Rex ! Il vivait dans le désert de Gobi en Mongolie.',
    desc: 'Le Tarbosaure était le T-Rex de l\'Asie ! Il vivait dans les déserts de Mongolie et ressemblait beaucoup à son cousin américain.',
    png: 'Tarbosaurus.png',
    color: '#96281b',
    continent: 'Asie',
    periode: 'cretace',
  },
  {
    id: 'albertosaurus',
    famille: 'trex',
    name: 'Albertosaure',
    full: 'Albertosaurus sarcophagus',
    cat: 'carnivores',
    epoque: 'Crétacé · il y a 70 millions d\'ans',
    region: 'Canada',
    taille_m: 9.5,
    hauteur_m: 3,
    poids_t: 2,
    comp_taille: _compLong(9.5),
    comp_hauteur: _compHaut(3),
    comp_poids: _compPoids(2),
    nom_etym: 'Son nom veut dire «lézard de l\'Alberta» — c\'est l\'endroit au Canada où on l\'a trouvé !',
    regime: '🥩 Carnivore',
    superpower: 'Chassait peut-être en meute ! Le loup des T-Rex !',
    chasseurs: 'Aucun de son époque',
    proies: 'Hadrosaures, cératopsiens',
    amis: 'Vivait peut-être en groupe — on a trouvé 26 squelettes ensemble !',
    fait: 'On a trouvé 26 Albertosaures ensemble au Canada ! Ils chassaient peut-être en groupe comme des loups !',
    desc: 'L\'Albertosaure était plus petit que le T-Rex mais il était très malin. Il chassait peut-être en groupe comme les loups d\'aujourd\'hui !',
    png: 'Albertosaurus.png',
    color: '#922b21',
    continent: 'Amérique du Nord',
    periode: 'cretace',
  },
  {
    id: 'gorgosaurus',
    famille: 'trex',
    name: 'Gorgosaure',
    full: 'Gorgosaurus libratus',
    cat: 'carnivores',
    epoque: 'Crétacé · il y a 76 millions d\'ans',
    region: 'Canada',
    taille_m: 9,
    hauteur_m: 2.8,
    poids_t: 2.5,
    comp_taille: _compLong(9),
    comp_hauteur: _compHaut(2.8),
    comp_poids: _compPoids(2.5),
    nom_etym: 'Son nom veut dire «lézard féroce» en grec — comme un monstre très très méchant !',
    regime: '🥩 Carnivore',
    superpower: 'Très rapide pour sa taille !',
    chasseurs: 'Aucun prédateur dans son territoire',
    proies: 'Hadrosaures, parasaurolophus',
    amis: 'Solitaire',
    fait: 'Le cousin canadien du T-Rex ! Il vivait avec les Parasaurolophus et les Ankylosaures.',
    desc: 'Le Gorgosaure était un grand chasseur du Canada il y a très longtemps. Il courait vite et avait des dents très tranchantes.',
    png: 'Gorgosaurus.png',
    color: '#a83232',
    continent: 'Amérique du Nord',
    periode: 'cretace',
  },
  {
    id: 'ceratosaurus',
    famille: 'trex',
    name: 'Cératosaure',
    full: 'Ceratosaurus nasicornis',
    cat: 'carnivores',
    epoque: 'Jurassique · il y a 150 millions d\'ans',
    region: 'Amérique du Nord, Afrique',
    taille_m: 5.5,
    hauteur_m: 2.5,
    poids_t: 0.7,
    comp_taille: _compLong(5.5),
    comp_hauteur: _compHaut(2.5),
    comp_poids: _compPoids(0.7),
    nom_etym: 'Son nom veut dire «lézard à corne» en grec — il avait une corne sur le nez !',
    regime: '🥩 Carnivore',
    superpower: 'Il avait UNE corne sur le nez — unique chez les grands carnivores !',
    chasseurs: 'Allosaure pouvait l\'affronter',
    proies: 'Petits dinosaures, poissons',
    amis: 'Solitaire',
    fait: 'Il avait des petites cornes sur la tête et une grande corne sur le nez — le seul grand carnivore avec une corne !',
    desc: 'Le Cératosaure avait quelque chose de spécial : une corne sur le nez ! Il vivait au Jurassique et chassait de petits animaux et des poissons.',
    png: 'Ceratosaurus.png',
    color: '#a04020',
    continent: 'Amérique du Nord',
    periode: 'jurassique',
  },
  {
    id: 'dilophosaurus',
    famille: 'trex',
    name: 'Dilophosaure',
    full: 'Dilophosaurus wetherilli',
    cat: 'carnivores',
    epoque: 'Jurassique · il y a 193 millions d\'ans',
    region: 'Amérique du Nord',
    taille_m: 7,
    hauteur_m: 2.4,
    poids_t: 0.43,
    comp_taille: _compLong(7),
    comp_hauteur: _compHaut(2.4),
    comp_poids: _compPoids(0.43),
    nom_etym: 'Son nom veut dire «lézard à deux crêtes» en grec — il avait deux jolies crêtes sur la tête !',
    regime: '🥩 Carnivore',
    superpower: '2 crêtes colorées sur la tête comme un chapeau de fête !',
    chasseurs: 'Prédateurs plus grands',
    proies: 'Petits dinos, charognes',
    amis: 'Peut-être en groupe',
    fait: 'Il avait 2 crêtes parallèles sur la tête — elles étaient probablement très colorées pour attirer les amis !',
    desc: 'Le Dilophosaure avait deux belles crêtes colorées sur la tête. C\'est un des premiers grands dinosaures carnivores !',
    png: 'Dilophosaurus.png',
    color: '#b05a00',
    continent: 'Amérique du Nord',
    periode: 'jurassique',
  },
  {
    id: 'carnotaurus',
    famille: 'trex',
    name: 'Carnotaure',
    full: 'Carnotaurus sastrei',
    cat: 'carnivores',
    epoque: 'Crétacé · il y a 72 millions d\'ans',
    region: 'Amérique du Sud',
    taille_m: 8,
    hauteur_m: 2.5,
    poids_t: 1.6,
    comp_taille: _compLong(8),
    comp_hauteur: _compHaut(2.5),
    comp_poids: _compPoids(1.6),
    nom_etym: 'Son nom veut dire «taureau qui mange de la viande» en latin — un taureau carnivore !',
    regime: '🥩 Carnivore',
    superpower: 'Le chasseur le PLUS RAPIDE parmi les grands carnivores — jusqu\'à 56 km/h !',
    chasseurs: 'Aucun dans son territoire',
    proies: 'Hadrosaures, dinosaures moyens',
    amis: 'Solitaire',
    fait: 'Il avait DE VRAIES CORNES au-dessus des yeux — comme un taureau ! Et il était ultra-rapide !',
    desc: 'Le Carnotaure avait des cornes comme un taureau et courait très très vite ! C\'est un des dinos les plus rapides de toute son époque.',
    png: 'Carnotaurus.png',
    color: '#7d3c00',
    continent: 'Amérique du Sud',
    periode: 'cretace',
  },
  {
    id: 'cryolophosaurus',
    famille: 'trex',
    name: 'Cryolophosaure',
    full: 'Cryolophosaurus ellioti',
    cat: 'carnivores',
    epoque: 'Jurassique · il y a 194 millions d\'ans',
    region: 'Antarctique !',
    taille_m: 6.5,
    hauteur_m: 2.5,
    poids_t: 0.4,
    comp_taille: _compLong(6.5),
    comp_hauteur: _compHaut(2.5),
    comp_poids: _compPoids(0.4),
    nom_etym: 'Son nom veut dire «lézard à crête de glace» en grec — il vivait en Antarctique, là où tout est gelé !',
    regime: '🥩 Carnivore',
    superpower: 'Vivait en Antarctique ! Le dino des neiges !',
    chasseurs: 'Prédateurs plus grands',
    proies: 'Herbivores de l\'Antarctique',
    amis: 'Inconnu',
    fait: 'Découvert en Antarctique ! Il vivait là quand c\'était encore chaud. Et il avait une crête bizarre peignée vers l\'avant — surnommé "Elvisaurus" !',
    desc: 'Le Cryolophosaure vivait en Antarctique quand il faisait encore un peu chaud là-bas ! Il avait une crête rigolote et on l\'appelle parfois Elvisaurus !',
    png: 'Cryolophosaurus.png',
    color: '#1a5276',
    continent: 'Antarctique',
    periode: 'jurassique',
  },

  // ══════════════ 2. GÉANTS HERBIVORES ══════════════

  {
    id: 'brachiosaurus',
    famille: 'cou_long',
    name: 'Brachiosaure',
    full: 'Brachiosaurus altithorax',
    cat: 'herbivores',
    epoque: 'Jurassique · il y a 150 millions d\'ans',
    region: 'Amérique du Nord, Afrique',
    taille_m: 22,
    hauteur_m: 13,
    poids_t: 47,
    queue_note: 'Chez lui, ce n\'est pas la queue qui fait la taille : c\'est son immense COU dressé vers le ciel !',
    comp_taille: _compLong(22),
    comp_hauteur: _compHaut(13),
    comp_poids: _compPoids(47),
    nom_etym: 'Son nom veut dire «lézard aux bras» en grec — ses pattes avant étaient plus longues que ses pattes arrière !',
    regime: '🌿 Herbivore',
    superpower: 'Mangeait les feuilles tout en haut des arbres que les autres ne pouvaient pas atteindre !',
    chasseurs: 'Seulement les très grands carnivores osaient attaquer les jeunes',
    proies: 'Mange des plantes',
    amis: 'Vivait en troupeau — plus fort ensemble !',
    fait: 'Sa tête était à 13 mètres de haut — aussi haut qu\'un immeuble de quatre étages ! Pour avaler, il avalait des pierres pour broyer sa nourriture dans son estomac.',
    desc: 'Le Brachiosaure était immense ! Il mangeait les feuilles tout en haut des arbres. Il avait un très long cou et de grandes pattes avant. Un géant gentil !',
    png: 'Brachiosaurus.png',
    color: '#1e8449',
    continent: 'Amérique du Nord',
    periode: 'jurassique',
  },
  {
    id: 'diplodocus',
    famille: 'cou_long',
    name: 'Diplodocus',
    full: 'Diplodocus longus',
    cat: 'herbivores',
    epoque: 'Jurassique · il y a 150 millions d\'ans',
    region: 'Amérique du Nord',
    taille_m: 27,
    hauteur_m: 4.5,
    poids_t: 12,
    queue_note: 'Sur ses 27 mètres, la queue-fouet fait presque la moitié — à peu près 13 mètres à elle toute seule !',
    comp_taille: _compLong(27),
    comp_hauteur: _compHaut(4.5),
    comp_poids: _compPoids(12),
    nom_etym: 'Son nom veut dire «double poutre» en grec — à cause de ses os de queue tout spéciaux !',
    regime: '🌿 Herbivore',
    superpower: 'Sa queue claquait comme un fouet — BOOM ! — pour faire peur aux chasseurs !',
    chasseurs: 'Allosaure, Ceratosaure pour les jeunes',
    proies: 'Mange des plantes',
    amis: 'En grand troupeau',
    fait: 'Sa queue faisait un BOOM supersonique en claquant ! Plus fort qu\'une explosion !',
    desc: 'Le Diplodocus était l\'un des plus longs dinosaures. Il avait un très long cou ET une très longue queue. Cette queue faisait un énorme bruit de fouet pour effrayer les chasseurs !',
    png: 'Diplodocus.png',
    color: '#239b56',
    continent: 'Amérique du Nord',
    periode: 'jurassique',
  },
  {
    id: 'apatosaurus',
    famille: 'cou_long',
    name: 'Apatosaure',
    full: 'Apatosaurus louisae',
    cat: 'herbivores',
    epoque: 'Jurassique · il y a 150 millions d\'ans',
    region: 'Amérique du Nord',
    taille_m: 22,
    hauteur_m: 4.5,
    poids_t: 23,
    queue_note: 'Une grande partie de sa longueur, c\'est sa très longue queue tenue à l\'horizontale.',
    comp_taille: _compLong(22),
    comp_hauteur: _compHaut(4.5),
    comp_poids: _compPoids(23),
    nom_etym: 'Son nom veut dire «lézard trompeur» en grec — ses os ont trompé les scientifiques pendant longtemps !',
    regime: '🌿 Herbivore',
    superpower: 'Un cou de 6 mètres pour manger des feuilles très haut !',
    chasseurs: 'Allosaure pour les jeunes',
    proies: 'Mange des plantes',
    amis: 'En troupeau',
    fait: 'Pendant longtemps, on l\'appelait "Brontosaure" — mais son vrai nom c\'est Apatosaure ! Il mangeait 250 kg de plantes PAR JOUR !',
    desc: 'L\'Apatosaure est le géant gentil que beaucoup appellent Brontosaure. Il mangeait autant de plantes en un jour que toi en une année !',
    png: 'Apatosaurus.png',
    color: '#196f3d',
    continent: 'Amérique du Nord',
    periode: 'jurassique',
  },
  {
    id: 'camarasaurus',
    famille: 'cou_long',
    name: 'Camarasaure',
    full: 'Camarasaurus lentus',
    cat: 'herbivores',
    epoque: 'Jurassique · il y a 155 millions d\'ans',
    region: 'Amérique du Nord',
    taille_m: 15,
    hauteur_m: 6,
    poids_t: 18,
    comp_taille: _compLong(15),
    comp_hauteur: _compHaut(6),
    comp_poids: _compPoids(18),
    nom_etym: 'Son nom veut dire «lézard à chambres» en grec — ses os avaient des petits trous comme des chambres !',
    regime: '🌿 Herbivore',
    superpower: 'Des dents épaisses pour mâcher des branches très dures !',
    chasseurs: 'Allosaure pour les jeunes',
    proies: 'Mange des plantes',
    amis: 'En troupeau avec ses petits',
    fait: 'Le sauropode le plus commun d\'Amérique du Nord ! Il avait de grandes fenêtres dans son crâne pour alléger sa tête.',
    desc: 'Le Camarasaure était un dinosaure géant avec une grosse tête et de fortes dents. Il vivait en troupeau et s\'occupait bien de ses bébés.',
    png: 'Camarasaurus.png',
    color: '#17a589',
    continent: 'Amérique du Nord',
    periode: 'jurassique',
  },
  {
    id: 'amargasaurus',
    famille: 'cou_long',
    name: 'Amargasaure',
    full: 'Amargasaurus cazaui',
    cat: 'herbivores',
    epoque: 'Crétacé · il y a 125 millions d\'ans',
    region: 'Amérique du Sud',
    taille_m: 10,
    hauteur_m: 2.5,
    poids_t: 3,
    comp_taille: _compLong(10),
    comp_hauteur: _compHaut(2.5),
    comp_poids: _compPoids(3),
    nom_etym: 'Son nom vient de «La Amarga», l\'endroit en Argentine où on l\'a découvert !',
    regime: '🌿 Herbivore',
    superpower: '2 rangées d\'épines sur le cou ! Pour se défendre ou attirer des amis !',
    chasseurs: 'Grands carnivores d\'Amérique du Sud',
    proies: 'Mange des plantes',
    amis: 'En petit groupe',
    fait: 'Il avait 2 rangées d\'épines IMMENSES sur le cou et le dos ! Comme un haie d\'épines vivante !',
    desc: 'L\'Amargasaure avait 2 rangées de grandes épines sur le cou et le dos. C\'était peut-être pour se défendre ou pour montrer à ses amis qu\'il était beau !',
    png: 'Amargasaurus.png',
    color: '#0e6655',
    continent: 'Amérique du Sud',
    periode: 'cretace',
  },
  {
    id: 'plateosaurus',
    famille: 'cou_long',
    name: 'Plateosaure',
    full: 'Plateosaurus engelhardti',
    cat: 'herbivores',
    epoque: 'Trias · il y a 210 millions d\'ans',
    region: 'Europe',
    taille_m: 8,
    hauteur_m: 2.8,
    poids_t: 2,
    comp_taille: _compLong(8),
    comp_hauteur: _compHaut(2.8),
    comp_poids: _compPoids(2),
    nom_etym: 'Son nom veut dire «lézard plat» en grec — ses os étaient tout plats !',
    regime: '🌿 Herbivore',
    superpower: 'L\'un des PREMIERS grands dinosaures herbivores — le pionnier !',
    chasseurs: 'Premiers grands carnivores du Trias',
    proies: 'Mange des plantes',
    amis: 'En troupeau',
    fait: 'Un des premiers grands dinos ! Il marchait sur 4 pattes mais pouvait se dresser sur 2 pour atteindre les hautes branches.',
    desc: 'Le Plateosaure était l\'un des premiers grands dinosaures. Il vivait au Trias, longtemps avant le T-Rex. Il pouvait se lever sur ses pattes arrière pour manger plus haut !',
    png: 'Plateosaurus.png',
    color: '#148f77',
    continent: 'Europe',
    periode: 'trias',
  },

  // ══════════════ 3. LES TOUT BLINDÉS ══════════════

  {
    id: 'ankylosaurus',
    famille: 'arme',
    name: 'Ankylosaure',
    full: 'Ankylosaurus magniventris',
    cat: 'herbivores',
    epoque: 'Crétacé · il y a 66 millions d\'ans',
    region: 'Amérique du Nord',
    taille_m: 7,
    hauteur_m: 1.8,
    poids_t: 6,
    comp_taille: _compLong(7),
    comp_hauteur: _compHaut(1.8),
    comp_poids: _compPoids(6),
    nom_etym: 'Son nom veut dire «lézard rigide» en grec — tout son dos était couvert d\'une armure dure !',
    regime: '🌿 Herbivore',
    superpower: 'Son dos était une armure de plaques osseuses + une queue-massue pour casser les os du T-Rex !',
    chasseurs: 'T-Rex essayait ! Mais c\'était très dur...',
    proies: 'Mange des plantes',
    amis: 'Solitaire ou petit groupe',
    fait: 'Sa queue-massue pouvait briser les os du T-Rex ! Même l\'os le plus solide !',
    desc: 'L\'Ankylosaure était le char d\'assaut des dinosaures ! Son dos était recouvert d\'une armure dure comme de la roche. Et sa queue finissait par une grosse boule qui cassait tout !',
    png: 'Ankylosaurus.png',
    color: '#626567',
    continent: 'Amérique du Nord',
    periode: 'cretace',
  },
  {
    id: 'euoplocephalus',
    famille: 'arme',
    name: 'Euoplocéphale',
    full: 'Euoplocephalus tutus',
    cat: 'herbivores',
    epoque: 'Crétacé · il y a 75 millions d\'ans',
    region: 'Canada',
    taille_m: 6,
    hauteur_m: 1.5,
    poids_t: 2.2,
    comp_taille: _compLong(6),
    comp_hauteur: _compHaut(1.5),
    comp_poids: _compPoids(2.2),
    nom_etym: 'Son nom veut dire «tête bien protégée» en grec — sa tête avait une armure tout autour !',
    regime: '🌿 Herbivore',
    superpower: 'Même ses paupières étaient blindées ! Rien ne pouvait le blesser !',
    chasseurs: 'Gorgosaure tentait l\'attaque',
    proies: 'Mange des plantes',
    amis: 'Solitaire',
    fait: 'Même SES YEUX avaient une armure osseuse ! Le dino le mieux protégé de toute l\'histoire !',
    desc: 'L\'Euoplocéphale était encore plus blindé que l\'Ankylosaure. Même ses paupières étaient faites d\'os ! Il avait aussi une queue-massue super puissante.',
    png: 'Euoplocephalus.png',
    color: '#717d7e',
    continent: 'Amérique du Nord',
    periode: 'cretace',
  },
  {
    id: 'stegosaurus',
    famille: 'arme',
    name: 'Stégosaure',
    full: 'Stegosaurus ungulatus',
    cat: 'herbivores',
    epoque: 'Jurassique · il y a 155 millions d\'ans',
    region: 'Amérique du Nord, Europe',
    taille_m: 9,
    hauteur_m: 2.8,
    poids_t: 4,
    comp_taille: _compLong(9),
    comp_hauteur: _compHaut(2.8),
    comp_poids: _compPoids(4),
    nom_etym: 'Son nom veut dire «lézard à toit» en grec — ses grandes plaques ressemblaient à des tuiles de maison !',
    regime: '🌿 Herbivore',
    superpower: 'Les grandes plaques sur son dos régulaient sa température comme un radiateur !',
    chasseurs: 'Allosaure — mais attention à la queue !',
    proies: 'Mange des plantes',
    amis: 'Peut-être en petit groupe',
    fait: 'Son cerveau était de la taille d\'une noix de noix ! Mais sa queue avec 4 piques pouvait percer l\'Allosaure !',
    desc: 'Le Stégosaure avait de grandes plaques colorées sur le dos et 4 longues piques au bout de la queue. Ses plaques lui servaient peut-être de radiateur pour se réchauffer ou se refroidir !',
    png: 'Stegosaurus.png',
    color: '#5d6d7e',
    continent: 'Amérique du Nord',
    periode: 'jurassique',
  },
  {
    id: 'kentrosaurus',
    famille: 'arme',
    name: 'Kéntrosaure',
    full: 'Kentrosaurus aethiopicus',
    cat: 'herbivores',
    epoque: 'Jurassique · il y a 155 millions d\'ans',
    region: 'Afrique (Tanzanie)',
    taille_m: 4.5,
    hauteur_m: 1.5,
    poids_t: 1,
    comp_taille: _compLong(4.5),
    comp_hauteur: _compHaut(1.5),
    comp_poids: _compPoids(1),
    nom_etym: 'Son nom veut dire «lézard pointu» en grec — il était couvert de pointes partout !',
    regime: '🌿 Herbivore',
    superpower: 'Des piques partout sur le dos ET sur les épaules — une forêt d\'épines !',
    chasseurs: 'Carnivores africains',
    proies: 'Mange des plantes',
    amis: 'Peut-être en troupeau',
    fait: 'Le cousin africain du Stégosaure ! Il avait encore plus de piques — jusqu\'aux épaules ! Même les carnivores évitaient de l\'attaquer par derrière.',
    desc: 'Le Kéntrosaure était le cousin africain du Stégosaure. Il était plus petit mais avait encore plus de piques sur tout le corps. Même sur les épaules !',
    png: 'Kentrosaurus.png',
    color: '#4d5656',
    continent: 'Afrique',
    periode: 'jurassique',
  },

  // ══════════════ 4. CRESTÉS & CORNUS ══════════════

  {
    id: 'triceratops',
    famille: 'cornu',
    name: 'Tricératops',
    full: 'Triceratops horridus',
    cat: 'herbivores',
    epoque: 'Crétacé · il y a 66 millions d\'ans',
    region: 'Amérique du Nord',
    taille_m: 9,
    hauteur_m: 3,
    poids_t: 9,
    comp_taille: _compLong(9),
    comp_hauteur: _compHaut(3),
    comp_poids: _compPoids(9),
    nom_etym: 'Son nom veut dire «face à trois cornes» en grec — il avait exactement trois belles cornes !',
    regime: '🌿 Herbivore',
    superpower: '3 cornes et une collerette osseuse géante — le bouclier parfait contre le T-Rex !',
    chasseurs: 'T-Rex — mais le Tricératops se défendait bien !',
    proies: 'Mange des plantes',
    amis: 'Peut-être en troupeau pour protéger les petits',
    fait: 'Ses cornes faisaient 1 mètre de long ! Et on a trouvé des os de T-Rex avec des marques de cornes de Tricératops — ils se battaient vraiment !',
    desc: 'Le Tricératops avait 3 cornes et un grand bouclier osseux autour de la tête. Il n\'avait pas peur du T-Rex ! C\'était le grand guerrier des herbivores.',
    png: 'Triceratops.png',
    color: '#7d6608',
    continent: 'Amérique du Nord',
    periode: 'cretace',
  },
  {
    id: 'torosaurus',
    famille: 'cornu',
    name: 'Torosaure',
    full: 'Torosaurus latus',
    cat: 'herbivores',
    epoque: 'Crétacé · il y a 66 millions d\'ans',
    region: 'Amérique du Nord',
    taille_m: 8,
    hauteur_m: 3,
    poids_t: 8,
    comp_taille: _compLong(8),
    comp_hauteur: _compHaut(3),
    comp_poids: _compPoids(8),
    nom_etym: 'Son nom veut dire «lézard perforé» en grec — à cause des grands trous dans sa collerette ! (souvent on croit que ça veut dire «lézard taureau», mais non !)',
    regime: '🌿 Herbivore',
    superpower: 'La plus grande tête de TOUS les animaux qui ont marché sur Terre — sa collerette faisait presque 3 mètres !',
    chasseurs: 'T-Rex — comme son cousin le Tricératops',
    proies: 'Mange des plantes',
    amis: 'Peut-être en petit groupe, comme les autres dinos à cornes',
    fait: 'Sa collerette avait des grands trous (des fenêtres !), alors que celle du Tricératops était toute pleine. C\'est comme ça qu\'on les reconnaît !',
    desc: 'Le Torosaure ressemblait beaucoup au Tricératops, mais avec une collerette ENCORE plus grande, percée de deux grands trous. Il avait le plus grand crâne de tous les animaux terrestres !',
    png: 'grok/torosaurus_lot1_1_taille.jpg',
    color: '#7d6608',
    continent: 'Amérique du Nord',
    periode: 'cretace',
  },
  {
    id: 'styracosaurus',
    famille: 'cornu',
    name: 'Styracosaure',
    full: 'Styracosaurus albertensis',
    cat: 'herbivores',
    epoque: 'Crétacé · il y a 75 millions d\'ans',
    region: 'Canada',
    taille_m: 5.5,
    hauteur_m: 1.8,
    poids_t: 2.7,
    comp_taille: _compLong(5.5),
    comp_hauteur: _compHaut(1.8),
    comp_poids: _compPoids(2.7),
    nom_etym: 'Son nom veut dire «lézard à piques» en grec — sa collerette avait plein de grandes pointes !',
    regime: '🌿 Herbivore',
    superpower: 'Une couronne de 6 grandes cornes autour de la collerette — le dino le plus décoré !',
    chasseurs: 'Gorgosaure, Albertosaure',
    proies: 'Mange des plantes',
    amis: 'En grand troupeau — on a trouvé des centaines ensemble !',
    fait: 'Sa collerette avait 6 grandes cornes ! C\'était peut-être pour attirer des amis ou faire peur aux ennemis.',
    desc: 'Le Styracosaure avait une magnifique couronne de cornes autour de la tête. Il vivait en grand troupeau pour se protéger des grands carnivores.',
    png: 'Styracosaurus.png',
    color: '#9a7d0a',
    continent: 'Amérique du Nord',
    periode: 'cretace',
  },
  {
    id: 'protoceratops',
    famille: 'cornu',
    name: 'Protocératops',
    full: 'Protoceratops andrewsi',
    cat: 'herbivores',
    epoque: 'Crétacé · il y a 75 millions d\'ans',
    region: 'Asie (Mongolie)',
    taille_m: 1.9,
    hauteur_m: 0.6,
    poids_t: 0.08,
    comp_taille: _compLong(1.9),
    comp_hauteur: _compHaut(0.6),
    comp_poids: _compPoids(0.08),
    nom_etym: 'Son nom veut dire «premier visage à corne» en grec — c\'est un ancêtre des dinos à cornes !',
    regime: '🌿 Herbivore',
    superpower: 'Le grand-père de tous les dinos à cornes ! Et une mâchoire très puissante.',
    chasseurs: 'Vélociraptor — et ils se battaient !',
    proies: 'Mange des plantes',
    amis: 'En troupeau avec des nids en groupe',
    fait: 'On a trouvé un fossile incroyable : un Vélociraptor et un Protocératops morts en train de se battre ! Ensevelis par une tempête de sable !',
    desc: 'Le Protocératops était le petit ancêtre des Tricératops. Il avait déjà une collerette mais pas encore de cornes. Et il se battait courageusement contre les Vélociraptors !',
    png: 'Protoceratops.png',
    color: '#b7950b',
    continent: 'Asie',
    periode: 'cretace',
  },
  {
    id: 'psittacosaurus',
    famille: 'cornu',
    name: 'Psittacosaure',
    full: 'Psittacosaurus mongoliensis',
    cat: 'herbivores',
    epoque: 'Crétacé · il y a 120 millions d\'ans',
    region: 'Asie',
    taille_m: 1.8,
    hauteur_m: 0.5,
    poids_t: 0.02,
    queue_note: 'Sa queue faisait presque la moitié de sa longueur.',
    comp_taille: _compLong(1.8),
    comp_hauteur: _compHaut(0.5),
    comp_poids: _compPoids(0.02),
    nom_etym: 'Son nom veut dire «lézard perroquet» en grec — sa tête ressemblait à un bec de perroquet !',
    regime: '🌿 Herbivore',
    superpower: 'Un bec de perroquet pour couper les plantes ! Et des plumes sur la queue !',
    chasseurs: 'Petits et grands carnivores d\'Asie',
    proies: 'Mange des plantes',
    amis: 'En groupe, les adultes gardaient les petits',
    fait: 'Un fossile montre un adulte avec 34 petits ! Il faisait la nounou pour toute la famille !',
    desc: 'Le Psittacosaure avait un bec comme un perroquet et de jolies plumes sur la queue. C\'est l\'ancêtre du Tricératops. Et les adultes gardaient les bébés comme une vraie école !',
    png: 'Psittacosaurus.png',
    color: '#9b7e04',
    continent: 'Asie',
    periode: 'cretace',
  },
  {
    id: 'centrosaurus',
    famille: 'cornu',
    name: 'Centrosaure',
    full: 'Centrosaurus apertus',
    cat: 'herbivores',
    epoque: 'Crétacé · il y a 76 millions d\'ans',
    region: 'Canada',
    taille_m: 5.5,
    hauteur_m: 1.8,
    poids_t: 2,
    comp_taille: _compLong(5.5),
    comp_hauteur: _compHaut(1.8),
    comp_poids: _compPoids(2),
    nom_etym: 'Son nom veut dire «lézard à pointes» en grec — sa collerette était bordée de petites pointes !',
    regime: '🌿 Herbivore',
    superpower: 'Une seule grande corne sur le nez, recourbée comme un croissant !',
    chasseurs: 'Gorgosaure — un grand cousin du T-Rex',
    proies: 'Mange des plantes',
    amis: 'En ÉNORMES troupeaux de milliers de dinos !',
    fait: 'On a trouvé des os de MILLIERS de Centrosaures ensemble ! Ils marchaient en troupeaux géants, comme un immense troupeau de vaches dans un pré, mais en dinosaures !',
    desc: 'Le Centrosaure avait une grande corne sur le nez et une collerette bordée de pointes. Il vivait en troupeaux immenses pour se protéger des grands carnivores.',
    png: 'grok/centrosaurus_lot2_1_taille.jpg',
    color: '#8a6d0a',
    continent: 'Amérique du Nord',
    periode: 'cretace',
  },
  {
    id: 'chasmosaurus',
    famille: 'cornu',
    name: 'Chasmosaure',
    full: 'Chasmosaurus belli',
    cat: 'herbivores',
    epoque: 'Crétacé · il y a 76 millions d\'ans',
    region: 'Canada',
    taille_m: 4.8,
    hauteur_m: 1.5,
    poids_t: 2,
    comp_taille: _compLong(4.8),
    comp_hauteur: _compHaut(1.5),
    comp_poids: _compPoids(2),
    nom_etym: 'Son nom veut dire «lézard à ouverture» en grec — sa collerette avait deux énormes trous !',
    regime: '🌿 Herbivore',
    superpower: 'Une immense collerette avec deux grands trous, comme deux hublots — légère mais impressionnante !',
    chasseurs: 'Gorgosaure',
    proies: 'Mange des plantes',
    amis: 'En troupeau, comme les autres dinos à cornes',
    fait: 'Sa grande collerette avait deux trous, comme deux hublots ! De la peau les recouvrait, comme la toile d\'un cerf-volant.',
    desc: 'Le Chasmosaure avait une collerette gigantesque avec deux grands trous. C\'était plus léger à porter qu\'une collerette toute pleine !',
    png: 'grok/chasmosaurus_lot2_1_taille.jpg',
    color: '#8a6d0a',
    continent: 'Amérique du Nord',
    periode: 'cretace',
  },
  {
    id: 'kosmoceratops',
    famille: 'cornu',
    name: 'Kosmocératops',
    full: 'Kosmoceratops richardsoni',
    cat: 'herbivores',
    epoque: 'Crétacé · il y a 76 millions d\'ans',
    region: 'États-Unis',
    taille_m: 4.5,
    hauteur_m: 1.5,
    poids_t: 1.2,
    comp_taille: _compLong(4.5),
    comp_hauteur: _compHaut(1.5),
    comp_poids: _compPoids(1.2),
    nom_etym: 'Son nom veut dire «face cornue ornée» en grec — c\'était le dino le plus décoré de tous !',
    regime: '🌿 Herbivore',
    superpower: 'Le RECORD du monde : QUINZE cornes sur la tête ! Personne n\'en a plus que lui.',
    chasseurs: 'Teratophoneus — un grand cousin du T-Rex',
    proies: 'Mange des plantes',
    amis: 'En troupeau dans les marais (comme une grande piscine de boue) de l\'Utah',
    fait: 'C\'est le dinosaure avec le PLUS de cornes au monde : QUINZE ! Des mini-cornes tombaient vers le bas comme une frange rigolote.',
    desc: 'Le Kosmocératops était le champion des cornes : quinze en tout ! Dix petits crochets se rabattaient vers l\'avant sur sa collerette, comme une couronne décorée.',
    png: 'grok/kosmoceratops_lot2_1_sa_vie.jpg',
    color: '#8a6d0a',
    continent: 'Amérique du Nord',
    periode: 'cretace',
  },
  {
    id: 'pachyrhinosaurus',
    famille: 'cornu',
    name: 'Pachyrhinosaure',
    full: 'Pachyrhinosaurus canadensis',
    cat: 'herbivores',
    epoque: 'Crétacé · il y a 72 millions d\'ans',
    region: 'Canada',
    taille_m: 7,
    hauteur_m: 2,
    poids_t: 4,
    comp_taille: _compLong(7),
    comp_hauteur: _compHaut(2),
    comp_poids: _compPoids(4),
    nom_etym: 'Son nom veut dire «lézard au nez épais» en grec — il avait une grosse bosse d\'os sur le nez !',
    regime: '🌿 Herbivore',
    superpower: 'Tous ses cousins ont une corne pointue… lui, NON ! Il a un gros casque d\'os tout plat sur le nez.',
    chasseurs: 'Albertosaure',
    proies: 'Mange des plantes',
    amis: 'En grand troupeau',
    fait: 'Au lieu d\'une corne, il avait un gros casque d\'os plat sur le nez. Il s\'en servait peut-être pour se cogner la tête contre ses copains, comme les vaches qui se poussent !',
    desc: 'Le Pachyrhinosaure n\'avait pas de corne mais une grosse bosse d\'os plate sur le nez, comme un casque. Il pouvait se cogner la tête contre ses copains sans se faire mal !',
    png: 'grok/pachyrhinosaurus_lot2_1_taille.jpg',
    color: '#8a6d0a',
    continent: 'Amérique du Nord',
    periode: 'cretace',
  },
  {
    id: 'pentaceratops',
    famille: 'cornu',
    name: 'Pentacératops',
    full: 'Pentaceratops sternbergii',
    cat: 'herbivores',
    epoque: 'Crétacé · il y a 75 millions d\'ans',
    region: 'États-Unis',
    taille_m: 6,
    hauteur_m: 2,
    poids_t: 5,
    comp_taille: _compLong(6),
    comp_hauteur: _compHaut(2),
    comp_poids: _compPoids(5),
    nom_etym: 'Son nom veut dire «face à cinq cornes» en grec — penta veut dire cinq ! (3 vraies cornes + 2 pointes sur les joues)',
    regime: '🌿 Herbivore',
    superpower: 'Une des plus GRANDES têtes de tous les animaux qui ont marché sur Terre — presque aussi grande qu\'un Papa !',
    chasseurs: 'Bistahieversor — un grand chasseur féroce',
    proies: 'Mange des plantes',
    amis: 'En troupeau',
    fait: 'Sa tête (avec la collerette) mesurait plus de 2 mètres : plus grande qu\'un Papa debout ! Une des plus grandes têtes du monde animal.',
    desc: 'Le Pentacératops avait «cinq cornes» : trois vraies, plus deux pointes sur les joues. Et une tête énorme, parmi les plus grandes de tous les animaux terrestres !',
    png: 'grok/pentaceratops_lot2_1_taille.jpg',
    color: '#8a6d0a',
    continent: 'Amérique du Nord',
    periode: 'cretace',
  },
  {
    id: 'anchiceratops',
    famille: 'cornu',
    name: 'Anchicératops',
    full: 'Anchiceratops ornatus',
    cat: 'herbivores',
    epoque: 'Crétacé · il y a 70 millions d\'ans',
    region: 'Canada',
    taille_m: 4.3,
    hauteur_m: 1.5,
    poids_t: 1.3,
    comp_taille: _compLong(4.3),
    comp_hauteur: _compHaut(1.5),
    comp_poids: _compPoids(1.3),
    nom_etym: 'Son nom veut dire «face cornue voisine» en grec — les savants l\'ont trouvé proche des autres dinos à cornes !',
    regime: '🌿 Herbivore',
    superpower: 'Sa collerette était bordée de gros boutons d\'os tout ronds, comme des billes collées tout autour !',
    chasseurs: 'Albertosaure',
    proies: 'Mange des plantes',
    amis: 'En troupeau près des rivières',
    fait: 'Tout autour de sa collerette, il y avait de gros boutons d\'os ronds, comme des billes collées ! Et sa collerette était presque carrée, comme une petite porte.',
    desc: 'L\'Anchicératops avait une collerette presque carrée, bordée de gros boutons d\'os ronds comme des billes. Une forme unique chez les dinos à cornes !',
    png: 'grok/anchiceratops_lot2_1_taille.jpg',
    color: '#8a6d0a',
    continent: 'Amérique du Nord',
    periode: 'cretace',
  },
  {
    id: 'diabloceratops',
    famille: 'cornu',
    name: 'Diablocératops',
    full: 'Diabloceratops eatoni',
    cat: 'herbivores',
    epoque: 'Crétacé · il y a 81 millions d\'ans',
    region: 'États-Unis',
    taille_m: 4.5,
    hauteur_m: 1.5,
    poids_t: 1.3,
    comp_taille: _compLong(4.5),
    comp_hauteur: _compHaut(1.5),
    comp_poids: _compPoids(1.3),
    nom_etym: 'Son nom veut dire «face cornue du diable» — diablo veut dire diable en espagnol, à cause de ses deux grandes cornes !',
    regime: '🌿 Herbivore',
    superpower: 'Deux grandes cornes dressées en haut de la collerette — comme des cornes de petit diable !',
    chasseurs: 'Lythronax — un cousin plus vieux du T-Rex',
    proies: 'Mange des plantes (oui, même avec son nom de diable !)',
    amis: 'En troupeau',
    fait: 'Avec ses deux cornes dressées, on dirait un vrai petit diable ! C\'est pour ça qu\'on l\'a appelé Diablo. Mais ne t\'inquiète pas : il ne mange que des plantes !',
    desc: 'Le Diablocératops avait deux grandes cornes dressées sur sa collerette, comme un diable. C\'est un des plus anciens dinos à cornes connus !',
    png: 'grok/diabloceratops_lot2_1_taille.jpg',
    color: '#8a6d0a',
    continent: 'Amérique du Nord',
    periode: 'cretace',
  },
  {
    id: 'einiosaurus',
    famille: 'cornu',
    name: 'Einiosaure',
    full: 'Einiosaurus procurvicornis',
    cat: 'herbivores',
    epoque: 'Crétacé · il y a 74 millions d\'ans',
    region: 'États-Unis',
    taille_m: 4.5,
    hauteur_m: 1.5,
    poids_t: 1.3,
    comp_taille: _compLong(4.5),
    comp_hauteur: _compHaut(1.5),
    comp_poids: _compPoids(1.3),
    nom_etym: 'Son nom veut dire «lézard-bison» (eini = bison chez les anciens peuples d\'Amérique) — et sa corne est «courbée vers l\'avant» !',
    regime: '🌿 Herbivore',
    superpower: 'Une corne sur le nez recourbée vers l\'avant, comme un décapsuleur de Papa ou un gros crochet !',
    chasseurs: 'Albertosaure',
    proies: 'Mange des plantes',
    amis: 'En troupeau',
    fait: 'Sa corne du nez se courbait vers l\'avant exactement comme un décapsuleur ! Aucun autre dino n\'a une corne en forme de crochet comme ça.',
    desc: 'L\'Einiosaure avait une corne sur le nez recourbée vers l\'avant, comme un ouvre-bouteille. C\'est sa marque unique parmi tous les dinos à cornes !',
    png: 'Einiosaurus.png',
    color: '#8a6d0a',
    continent: 'Amérique du Nord',
    periode: 'cretace',
  },
  {
    id: 'utahceratops',
    famille: 'cornu',
    name: 'Utahcératops',
    full: 'Utahceratops gettyi',
    cat: 'herbivores',
    epoque: 'Crétacé · il y a 76 millions d\'ans',
    region: 'États-Unis',
    taille_m: 6,
    hauteur_m: 1.8,
    poids_t: 3.5,
    comp_taille: _compLong(6),
    comp_hauteur: _compHaut(1.8),
    comp_poids: _compPoids(3.5),
    nom_etym: 'Son nom veut dire «face cornue de l\'Utah» — comme l\'État américain où on l\'a trouvé !',
    regime: '🌿 Herbivore',
    superpower: 'Ses cornes ne pointent pas devant, mais sur les CÔTÉS, comme une vache !',
    chasseurs: 'Teratophoneus — un grand chasseur féroce',
    proies: 'Mange des plantes',
    amis: 'En troupeau, avec le Kosmocératops !',
    fait: 'Ses cornes pointaient sur les côtés, comme une vache, pas vers l\'avant comme Tritri ! Et il habitait le même marais que le Kosmocératops : deux géants à cornes voisins.',
    desc: 'L\'Utahcératops avait des cornes au-dessus des yeux pointant sur les côtés, comme des cornes de vache. Il partageait son marais (une grande piscine de boue) avec le Kosmocératops !',
    png: 'grok/utahceratops_lot2_1_taille.jpg',
    color: '#8a6d0a',
    continent: 'Amérique du Nord',
    periode: 'cretace',
  },
  {
    id: 'parasaurolophus',
    famille: 'bec',
    name: 'Parasaurolophus',
    full: 'Parasaurolophus walkeri',
    cat: 'herbivores',
    epoque: 'Crétacé · il y a 76 millions d\'ans',
    region: 'Amérique du Nord',
    taille_m: 10,
    hauteur_m: 3.5,
    poids_t: 2.5,
    comp_taille: _compLong(10),
    comp_hauteur: _compHaut(3.5),
    comp_poids: _compPoids(2.5),
    nom_etym: 'Son nom veut dire «près du lézard à crête» en grec — il avait une grande corne creuse pour faire des sons !',
    regime: '🌿 Herbivore',
    superpower: 'Sa crête était un instrument de musique ! Il soufflait dedans pour faire des sons très forts !',
    chasseurs: 'T-Rex, Gorgosaure',
    proies: 'Mange des plantes',
    amis: 'En grand troupeau — les cris avertissaient le groupe du danger !',
    fait: 'Sa crête creuse faisait des sons comme un trombone ! On peut reconstruire sa musique en ordinateur !',
    desc: 'Le Parasaurolophus avait une grande crête creuse sur la tête. Il soufflait de l\'air dedans pour faire des sons très forts — comme un grand klaxon — pour parler avec son troupeau !',
    png: 'Parasaurolophus.png',
    color: '#6e2f8a',
    continent: 'Amérique du Nord',
    periode: 'cretace',
  },
  {
    id: 'corythosaurus',
    famille: 'bec',
    name: 'Corythosaure',
    full: 'Corythosaurus casuarius',
    cat: 'herbivores',
    epoque: 'Crétacé · il y a 77 millions d\'ans',
    region: 'Canada',
    taille_m: 8,
    hauteur_m: 3,
    poids_t: 3.5,
    comp_taille: _compLong(8),
    comp_hauteur: _compHaut(3),
    comp_poids: _compPoids(3.5),
    nom_etym: 'Son nom veut dire «lézard au casque de Corinthe» en grec — sa crête ressemblait à un casque de chevalier !',
    regime: '🌿 Herbivore',
    superpower: 'Sa crête en forme de casque servait de klaxon ET de radiateur !',
    chasseurs: 'T-Rex, Gorgosaure',
    proies: 'Mange des plantes',
    amis: 'En grand troupeau',
    fait: 'Sa crête ressemblait au casque d\'un soldat grec ! Elle était probablement très colorée pour reconnaître les membres de sa famille.',
    desc: 'Le Corythosaure portait une grande crête en forme de casque sur la tête. Cette crête lui servait à faire des sons pour parler avec ses amis du troupeau.',
    png: 'Corythosaurus.png',
    color: '#7d3c98',
    continent: 'Amérique du Nord',
    periode: 'cretace',
  },
  {
    id: 'edmontosaurus',
    famille: 'bec',
    name: 'Edmontosaure',
    full: 'Edmontosaurus regalis',
    cat: 'herbivores',
    epoque: 'Crétacé · il y a 68 millions d\'ans',
    region: 'Amérique du Nord',
    taille_m: 12,
    hauteur_m: 3.5,
    poids_t: 4,
    comp_taille: _compLong(12),
    comp_hauteur: _compHaut(3.5),
    comp_poids: _compPoids(4),
    nom_etym: 'Son nom veut dire «lézard d\'Edmonton» — c\'est une ville du Canada où on a trouvé ses os !',
    regime: '🌿 Herbivore',
    superpower: 'Des centaines de dents pour mâcher — jamais à court de dents de rechange !',
    chasseurs: 'T-Rex — sa proie préférée !',
    proies: 'Mange des plantes',
    amis: 'En très grand troupeau — des milliers ensemble !',
    fait: 'Il avait jusqu\'à 1000 petites dents qui se remplaçaient sans cesse ! Quand une tombait, une nouvelle poussait.',
    desc: 'L\'Edmontosaure était un grand dino à bec de canard. Il vivait en immenses troupeaux et avait des centaines de dents pour broyer les plantes les plus dures !',
    png: 'Edmontosaurus.png',
    color: '#8e44ad',
    continent: 'Amérique du Nord',
    periode: 'cretace',
  },
  {
    id: 'maiasaura',
    famille: 'bec',
    name: 'Maiasaura',
    full: 'Maiasaura peeblesorum',
    cat: 'herbivores',
    epoque: 'Crétacé · il y a 77 millions d\'ans',
    region: 'Amérique du Nord',
    taille_m: 9,
    hauteur_m: 2.5,
    poids_t: 3,
    comp_taille: _compLong(9),
    comp_hauteur: _compHaut(2.5),
    comp_poids: _compPoids(3),
    nom_etym: 'Son nom veut dire «lézard bonne maman» en grec — on a trouvé ses nids avec ses bébés, elle prenait soin d\'eux !',
    regime: '🌿 Herbivore',
    superpower: 'La meilleure maman dinosaure ! Elle nourrissait ses bébés dans le nid pendant des mois !',
    chasseurs: 'T-Rex, grands carnivores',
    proies: 'Mange des plantes',
    amis: 'En colonies avec des centaines de nids ensemble — comme un village !',
    fait: 'Son nom veut dire "bonne maman lézard" ! On a trouvé ses nids avec des œufs et des bébés — elle les nourrissait dans le nid !',
    desc: 'La Maiasaura était la meilleure maman de tous les dinosaures ! Elle construisait des nids, pondait des œufs, et nourrissait ses bébés pendant longtemps. Elle vivait en grand village avec d\'autres familles !',
    png: 'Maiasaura.png',
    color: '#9b59b6',
    continent: 'Amérique du Nord',
    periode: 'cretace',
  },
  {
    id: 'iguanodon',
    famille: 'bec',
    name: 'Iguanodon',
    full: 'Iguanodon bernissartensis',
    cat: 'herbivores',
    epoque: 'Crétacé · il y a 125 millions d\'ans',
    region: 'Europe, Amérique du Nord',
    taille_m: 10,
    hauteur_m: 2.7,
    poids_t: 3,
    comp_taille: _compLong(10),
    comp_hauteur: _compHaut(2.7),
    comp_poids: _compPoids(3),
    nom_etym: 'Son nom veut dire «dent d\'iguane» en grec — ses dents ressemblaient exactement à celles d\'un iguane !',
    regime: '🌿 Herbivore',
    superpower: 'Un pique osseux sur le pouce — comme un couteau sur la main !',
    chasseurs: 'Baryonyx, Carnosaures',
    proies: 'Mange des plantes',
    amis: 'En troupeau',
    fait: 'C\'est l\'un des PREMIERS dinosaures découverts en 1820 ! Au début, on croyait que la corne du pouce était sa corne nasale !',
    desc: 'L\'Iguanodon était un dino célèbre car c\'est l\'un des premiers découverts. Il avait un pique tranchant sur le pouce pour se défendre. Il marchait sur 4 pattes mais pouvait se lever sur 2 !',
    png: 'Iguanodon.png',
    color: '#a569bd',
    continent: 'Europe',
    periode: 'cretace',
  },
  {
    id: 'pachycephalosaurus',
    famille: 'bizarre',
    name: 'Pachycéphalosaure',
    full: 'Pachycephalosaurus wyomingensis',
    cat: 'herbivores',
    epoque: 'Crétacé · il y a 70 millions d\'ans',
    region: 'Amérique du Nord',
    taille_m: 4.5,
    hauteur_m: 1.5,
    poids_t: 0.45,
    comp_taille: _compLong(4.5),
    comp_hauteur: _compHaut(1.5),
    comp_poids: _compPoids(0.45),
    nom_etym: 'Son nom veut dire «lézard à tête épaisse» en grec — son crâne était épais comme un casque de 25 centimètres !',
    regime: '🌿 Herbivore (et peut-être des insectes)',
    superpower: 'Un crâne de 25 cm d\'épaisseur ! Il se battait en se frappant la tête comme les béliers !',
    chasseurs: 'T-Rex, grands carnivores',
    proies: 'Mange des plantes',
    amis: 'En groupe',
    fait: 'Son crâne mesurait 25 cm d\'épaisseur — presque autant que ta tête entière ! Il faisait des joutes comme les béliers !',
    desc: 'Le Pachycephalosaure avait un crâne super épais, comme un casque de moto en os ! Les mâles se battaient en se frappant la tête comme les béliers font aujourd\'hui.',
    png: 'Pachycephalosaurus.png',
    color: '#884ea0',
    continent: 'Amérique du Nord',
    periode: 'cretace',
  },

  // ══════════════ 5. RAPACES MALINS ══════════════

  {
    id: 'velociraptor',
    famille: 'raptor',
    name: 'Vélociraptor',
    full: 'Velociraptor mongoliensis',
    cat: 'carnivores',
    epoque: 'Crétacé · il y a 75 millions d\'ans',
    region: 'Asie (Mongolie)',
    taille_m: 2,
    hauteur_m: 0.5,
    poids_t: 0.015,
    queue_note: 'Sa queue raide faisait la moitié de sa longueur : voilà pourquoi il est tout petit mais tout en longueur !',
    comp_taille: _compLong(2),
    comp_hauteur: _compHaut(0.5),
    comp_poids: _compPoids(0.015),
    nom_etym: 'Son nom veut dire «voleur rapide» en latin — il courait très vite pour attraper sa nourriture !',
    regime: '🥩 Carnivore',
    superpower: 'Ultra-malin, chassait en équipe, et avait une grande griffe rétractable !',
    chasseurs: 'Grands carnivores',
    proies: 'Protocératops, petits dinos',
    amis: 'En meute — le loup des dinos !',
    fait: 'Le vrai Vélociraptor était de la taille d\'un dindon ! Et il avait DES PLUMES ! Rien à voir avec Jurassic Park !',
    desc: 'Le Vélociraptor n\'était pas énorme — de la taille d\'un grand chien. Mais il était couvert de plumes et très très malin ! Il chassait en groupe comme les loups.',
    png: 'Velociraptor.png',
    color: '#d35400',
    continent: 'Asie',
    periode: 'cretace',
  },
  {
    id: 'deinonychus',
    famille: 'raptor',
    name: 'Deinonychus',
    full: 'Deinonychus antirrhopus',
    cat: 'carnivores',
    epoque: 'Crétacé · il y a 115 millions d\'ans',
    region: 'Amérique du Nord',
    taille_m: 3.4,
    hauteur_m: 0.9,
    poids_t: 0.08,
    comp_taille: _compLong(3.4),
    comp_hauteur: _compHaut(0.9),
    comp_poids: _compPoids(0.08),
    nom_etym: 'Son nom veut dire «griffe terrible» en grec — il avait une grande griffe recourbée très coupante !',
    regime: '🥩 Carnivore',
    superpower: 'Sa grande griffe de 13 cm était une arme mortelle pour accrocher sa proie !',
    chasseurs: 'Grands carnivores',
    proies: 'Iguanodon, dinos moyens',
    amis: 'En meute de chasseurs',
    fait: 'C\'est le vrai "raptor" de Jurassic Park ! Les Vélociraptors du film ressemblent en fait au Deinonychus !',
    desc: 'Le Deinonychus était le vrai modèle des raptors de Jurassic Park ! Il avait une énorme griffe tranchante et chassait en groupe. Super rapide et super malin !',
    png: 'Deinonychus.png',
    color: '#e67e22',
    continent: 'Amérique du Nord',
    periode: 'cretace',
  },
  {
    id: 'utahraptor',
    famille: 'raptor',
    name: 'Utahraptor',
    full: 'Utahraptor ostrommaysorum',
    cat: 'carnivores',
    epoque: 'Crétacé · il y a 126 millions d\'ans',
    region: 'Amérique du Nord',
    taille_m: 6,
    hauteur_m: 2,
    poids_t: 0.5,
    comp_taille: _compLong(6),
    comp_hauteur: _compHaut(2),
    comp_poids: _compPoids(0.5),
    nom_etym: 'Son nom veut dire «voleur de l\'Utah» — l\'Utah est l\'endroit aux États-Unis où on l\'a trouvé !',
    regime: '🥩 Carnivore',
    superpower: 'La plus grande griffe de tous les raptors — 24 cm ! Un couteau de cuisine géant !',
    chasseurs: 'Aucun de son époque n\'osait l\'attaquer',
    proies: 'Grands herbivores',
    amis: 'Peut-être en meute',
    fait: 'Sa griffe faisait 24 cm — aussi longue que ta main entière ! C\'est le plus grand raptor qui ait jamais existé !',
    desc: 'L\'Utahraptor était un GÉANT parmi les raptors ! Il avait une griffe énorme, courait vite, et était très intelligent. Le super prédateur de son époque !',
    png: 'Utahraptor.png',
    color: '#ca6f1e',
    continent: 'Amérique du Nord',
    periode: 'cretace',
  },
  {
    id: 'microraptor',
    famille: 'raptor',
    name: 'Microraptor',
    full: 'Microraptor gui',
    cat: 'volants_marins',
    epoque: 'Crétacé · il y a 120 millions d\'ans',
    region: 'Chine',
    taille_m: 0.77,
    hauteur_m: 0.3,
    poids_t: 0.001,
    comp_taille: _compLong(0.77),
    comp_hauteur: _compHaut(0.3),
    comp_poids: _compPoids(0.001),
    nom_etym: 'Son nom veut dire «petit voleur» en grec — c\'était un tout petit dinosaure à quatre ailes !',
    regime: '🥩 Carnivore',
    superpower: '4 ailes ! Planait entre les arbres comme un écureuil volant !',
    chasseurs: 'Autres carnivores, grands reptiles',
    proies: 'Lézards, petits mammifères, poissons',
    amis: 'Solitaire ou petit groupe',
    fait: 'Il avait 4 ailes — 2 sur les bras ET 2 sur les jambes ! Il planait entre les arbres comme un avion miniature !',
    desc: 'Le Microraptor était minuscule avec 4 ailes ! Il planait entre les arbres en Chine pour attraper des lézards et des petits poissons. Incroyable !',
    png: 'Microraptor.png',
    color: '#a04000',
    continent: 'Asie',
    periode: 'cretace',
  },
  {
    id: 'troodon',
    famille: 'raptor',
    name: 'Troodon',
    full: 'Troodon formosus',
    cat: 'omnivores',
    epoque: 'Crétacé · il y a 75 millions d\'ans',
    region: 'Amérique du Nord',
    taille_m: 2.2,
    hauteur_m: 0.9,
    poids_t: 0.05,
    comp_taille: _compLong(2.2),
    comp_hauteur: _compHaut(0.9),
    comp_poids: _compPoids(0.05),
    nom_etym: 'Son nom veut dire «dent blessante» en grec — ses petites dents avaient des bords tranchants !',
    regime: '🥩 Carnivore (et omnivore)',
    superpower: 'Le dinosaure le plus INTELLIGENT ! Le plus grand cerveau par rapport à sa taille !',
    chasseurs: 'Grands carnivores',
    proies: 'Petits mammifères, lézards',
    amis: 'En groupe, peut-être s\'occupait des œufs',
    fait: 'Certains scientifiques pensent que si les dinos n\'avaient pas disparu, le Troodon aurait pu devenir aussi intelligent qu\'un humain en quelques millions d\'années !',
    desc: 'Le Troodon était le dinosaure le plus intelligent de tous ! Il avait de grands yeux pour voir la nuit, de longs bras habiles, et un cerveau énorme. Le professeur des dinosaures !',
    png: 'Troodon.png',
    color: '#b7770d',
    continent: 'Amérique du Nord',
    periode: 'cretace',
  },
  {
    id: 'gallimimus',
    famille: 'raptor',
    name: 'Gallimimus',
    full: 'Gallimimus bullatus',
    cat: 'omnivores',
    epoque: 'Crétacé · il y a 70 millions d\'ans',
    region: 'Asie (Mongolie)',
    taille_m: 6,
    hauteur_m: 2,
    poids_t: 0.44,
    comp_taille: _compLong(6),
    comp_hauteur: _compHaut(2),
    comp_poids: _compPoids(0.44),
    nom_etym: 'Son nom veut dire «qui imite la poule» en latin — il ressemblait à une très grande poule qui court vite !',
    regime: '🌿 Omnivore (mange tout !)',
    superpower: 'Le dino le plus RAPIDE — jusqu\'à 70 km/h ! Plus vite qu\'un cheval au galop !',
    chasseurs: 'T-Rex, grands carnivores',
    proies: 'Petits animaux, œufs, plantes',
    amis: 'En grand troupeau — comme les autruches',
    fait: 'Il courait à 70 km/h — aussi vite qu\'une voiture en ville ! Personne ne pouvait l\'attraper.',
    desc: 'Le Gallimimus était le champion de la vitesse ! Il ressemblait à une grande autruche et courait en grand troupeau. Tellement rapide que même le T-Rex ne pouvait pas l\'attraper !',
    png: 'Gallimimus.png',
    color: '#d4a017',
    continent: 'Asie',
    periode: 'cretace',
  },
  {
    id: 'coelophysis',
    famille: 'raptor',
    name: 'Coelophysis',
    full: 'Coelophysis bauri',
    cat: 'carnivores',
    epoque: 'Trias · il y a 210 millions d\'ans',
    region: 'Amérique du Nord',
    taille_m: 3,
    hauteur_m: 1,
    poids_t: 0.02,
    queue_note: 'Sa longue queue raide faisait plus de la moitié de sa longueur.',
    comp_taille: _compLong(3),
    comp_hauteur: _compHaut(1),
    comp_poids: _compPoids(0.02),
    nom_etym: 'Son nom veut dire «forme creuse» en grec — ses os étaient creux et légers comme les oiseaux !',
    regime: '🥩 Carnivore',
    superpower: 'L\'un des PREMIERS carnivores ! Le grand-père de tous les raptors !',
    chasseurs: 'Premiers grands reptiles du Trias',
    proies: 'Petits lézards, insectes, poissons',
    amis: 'En meute — on a trouvé des centaines ensemble !',
    fait: 'On a trouvé des centaines de squelettes ensemble au Nouveau-Mexique ! Ils se seraient groupés pour survivre à une catastrophe.',
    desc: 'Le Coelophysis était l\'un des tout premiers dinosaures. Petit et rapide, il chassait en meute. C\'est le grand ancêtre de tous les raptors qui viendront bien plus tard !',
    png: 'Coelophysis.png',
    color: '#b7770d',
    continent: 'Amérique du Nord',
    periode: 'trias',
  },
  {
    id: 'compsognathus',
    famille: 'raptor',
    name: 'Compsognathus',
    full: 'Compsognathus longipes',
    cat: 'carnivores',
    epoque: 'Jurassique · il y a 150 millions d\'ans',
    region: 'Europe',
    taille_m: 1,
    hauteur_m: 0.3,
    poids_t: 0.003,
    comp_taille: _compLong(1),
    comp_hauteur: _compHaut(0.3),
    comp_poids: _compPoids(0.003),
    nom_etym: 'Son nom veut dire «mâchoire élégante» en grec — il avait une toute petite mâchoire très fine !',
    regime: '🥩 Carnivore',
    superpower: 'Le plus PETIT dinosaure connu ! Rapide comme l\'éclair !',
    chasseurs: 'Tous les carnivores',
    proies: 'Lézards, insectes',
    amis: 'Solitaire',
    fait: 'Il était de la taille d\'un poulet ! Pendant longtemps on croyait que c\'était le plus petit dino. Il courait peut-être à 64 km/h !',
    desc: 'Le Compsognathus était minuscule — de la taille d\'un poulet ! Mais il courait très vite pour attraper des lézards et des insectes. Le plus petit chasseur du Jurassique !',
    png: 'Compsognathus.png',
    color: '#c27b00',
    continent: 'Europe',
    periode: 'jurassique',
  },
  {
    id: 'oviraptor',
    famille: 'raptor',
    name: 'Oviraptor',
    full: 'Oviraptor philoceratops',
    cat: 'omnivores',
    epoque: 'Crétacé · il y a 75 millions d\'ans',
    region: 'Asie (Mongolie)',
    taille_m: 2,
    hauteur_m: 0.9,
    poids_t: 0.025,
    comp_taille: _compLong(2),
    comp_hauteur: _compHaut(0.9),
    comp_poids: _compPoids(0.025),
    nom_etym: 'Son nom veut dire «voleur d\'œufs» en latin — on croyait qu\'il volait des œufs, mais c\'était les siens qu\'il gardait !',
    regime: '🥩 Omnivore (mange tout !)',
    superpower: 'Une crête colorée de perroquet ET un papa poule — il couvait ses œufs !',
    chasseurs: 'Velociraptor, carnivores',
    proies: 'Œufs (peut-être), plantes, petits animaux',
    amis: 'En couple pour élever les petits',
    fait: 'Son nom veut dire "voleur d\'œufs"... mais c\'était un mensonge ! On a découvert qu\'il couvait SES PROPRES œufs comme les oiseaux !',
    desc: 'L\'Oviraptor a été injustement accusé de voler des œufs — en fait il couvait les siens comme un oiseau ! Il avait une belle crête colorée et était un excellent papa !',
    png: 'Oviraptor.png',
    color: '#d68910',
    continent: 'Asie',
    periode: 'cretace',
  },

  // ══════════════ 6. AIRS, MERS & BIZARRES ══════════════

  {
    id: 'pteranodon',
    famille: 'volant',
    name: 'Ptéranodon',
    alias: 'Ptérodactyle',
    full: 'Pteranodon longiceps',
    cat: 'volants_marins',
    epoque: 'Crétacé · il y a 85 millions d\'ans',
    region: 'Amérique du Nord (Kansas)',
    taille_m: 6,
    hauteur_m: 1.8,
    poids_t: 0.025,
    taille_vol: true,
    comp_taille: 'ses ailes ouvertes étaient larges comme une voiture et demie !',
    comp_hauteur: _compHaut(1.8),
    comp_poids: _compPoids(0.025),
    nom_etym: 'Son nom veut dire «aile sans dents» en grec — il volait avec de grandes ailes mais n\'avait pas de dents !',
    regime: '🐟 Piscivore',
    superpower: 'Volait sans effort en planant sur les courants chauds — le roi des airs !',
    chasseurs: 'Mosasaurus dans l\'eau',
    proies: 'Gros poissons, calmars',
    amis: 'En colonies sur les falaises',
    fait: 'Pas un vrai dino — un reptile volant ! Sa crête orientait son vol comme un gouvernail. Il plongeait pour attraper des poissons.',
    desc: 'Le Ptéranodon n\'était pas un dinosaure mais un reptile volant ! Il avait une envergure énorme et planait sur les vents. Il pêchait en plongeant dans la mer comme un pélican géant !',
    png: 'Pteranodon.png',
    color: '#1a5276',
    continent: 'Amérique du Nord',
    periode: 'cretace',
  },
  {
    id: 'quetzalcoatlus',
    famille: 'volant',
    name: 'Quetzalcoatlus',
    full: 'Quetzalcoatlus northropi',
    cat: 'volants_marins',
    epoque: 'Crétacé · il y a 68 millions d\'ans',
    region: 'Amérique du Nord',
    taille_m: 11,
    hauteur_m: 5,
    poids_t: 0.2,
    taille_vol: true,
    comp_taille: 'ses ailes ouvertes étaient larges comme un bus de Paris !',
    comp_hauteur: _compHaut(5),
    comp_poids: _compPoids(0.2),
    nom_etym: 'Son nom vient de Quetzalcoatl, le grand serpent plumé des dieux aztèques — un nom de dieu pour le plus grand volant !',
    regime: '🥩 Carnivore (charognes, petits dinos)',
    superpower: 'Le plus grand animal volant de TOUS LES TEMPS ! Debout, presque trois Papas l\'un sur l\'autre !',
    chasseurs: 'Aucun ne pouvait l\'attraper dans les airs',
    proies: 'Petits dinosaures, charognes',
    amis: 'Solitaire ou petit groupe',
    fait: 'Debout au sol il mesurait 5 mètres de haut — presque trois Papas l\'un sur l\'autre… et pourtant il VOLAIT ! Le plus grand être volant qui ait jamais existé !',
    desc: 'Le Quetzalcoatlus était le plus grand être volant de toute l\'histoire de la Terre ! Debout, il était presque aussi haut que trois Papas l\'un sur l\'autre. Il volait sur des milliers de kilomètres.',
    png: 'Quetzalcoatlus.png',
    color: '#1f618d',
    continent: 'Amérique du Nord',
    periode: 'cretace',
  },
  {
    id: 'archaeopteryx',
    famille: 'volant',
    name: 'Archaeoptéryx',
    full: 'Archaeopteryx lithographica',
    cat: 'volants_marins',
    epoque: 'Jurassique · il y a 150 millions d\'ans',
    region: 'Europe (Allemagne)',
    taille_m: 0.5,
    hauteur_m: 0.3,
    poids_t: 0.001,
    comp_taille: _compLong(0.5),
    comp_hauteur: _compHaut(0.3),
    comp_poids: _compPoids(0.001),
    nom_etym: 'Son nom veut dire «aile ancienne» en grec — c\'est l\'un des tout premiers oiseaux de l\'histoire !',
    regime: '🥩 Carnivore',
    superpower: 'Le PREMIER oiseau du monde ! Le chaînon entre dinosaures et oiseaux !',
    chasseurs: 'Prédateurs plus grands',
    proies: 'Insectes, petits lézards',
    amis: 'Solitaire',
    fait: 'C\'est l\'ANCÊTRE DE TOUS LES OISEAUX ! Il avait des plumes ET des dents ET des griffes. Le fossile le plus précieux du monde !',
    desc: 'L\'Archaeoptéryx est l\'ancêtre de tous les oiseaux ! Il avait des plumes comme un oiseau mais aussi des dents et des griffes de dino. C\'est le premier oiseau du monde entier !',
    png: 'Archaeopteryx.png',
    color: '#2e86c1',
    continent: 'Europe',
    periode: 'jurassique',
  },
  {
    id: 'mosasaurus',
    famille: 'volant',
    name: 'Mosasaure',
    full: 'Mosasaurus hoffmannii',
    cat: 'volants_marins',
    epoque: 'Crétacé · il y a 70 millions d\'ans',
    region: 'Toutes les mers du monde',
    taille_m: 17,
    hauteur_m: 2,
    poids_t: 10,
    comp_taille: _compLong(17),
    comp_hauteur: 'son corps était large comme la voiture de Papa !',
    comp_poids: _compPoids(10),
    nom_etym: 'Son nom veut dire «lézard de la Meuse» — la Meuse est une rivière en Europe où on a trouvé ses os !',
    regime: '🐟 Carnivore marin',
    superpower: 'Le monstre marin — roi absolu de toutes les mers du Crétacé !',
    chasseurs: 'Aucun — il était au sommet',
    proies: 'Requins, grands poissons, ptérosaures',
    amis: 'Solitaire (territoriau)',
    fait: 'Il attrapait même les ptérosaures en plein vol ! Et il mangeait des requins pour le petit déjeuner !',
    desc: 'Le Mosasaure était le monstre des mers préhistoriques ! Énorme comme un bus géant, il régnait sur tous les océans. Il mangeait même les requins et les ptérosaures !',
    png: 'Mosasaurus.png',
    color: '#154360',
    continent: 'Europe',
    periode: 'cretace',
  },
  {
    id: 'suchomimus',
    famille: 'volant',
    name: 'Suchomimus',
    full: 'Suchomimus tenerensis',
    cat: 'piscivores',
    epoque: 'Crétacé · il y a 112 millions d\'ans',
    region: 'Afrique (Niger)',
    taille_m: 11,
    hauteur_m: 3.5,
    poids_t: 4.5,
    comp_taille: _compLong(11),
    comp_hauteur: _compHaut(3.5),
    comp_poids: _compPoids(4.5),
    nom_etym: 'Son nom veut dire «qui imite le crocodile» en grec — son museau long ressemblait exactement à celui d\'un crocodile !',
    regime: '🐟 Piscivore',
    superpower: 'Un long museau comme un crocodile pour attraper des poissons géants !',
    chasseurs: 'Grands carnivores d\'Afrique',
    proies: 'Poissons géants, crocodiles',
    amis: 'Peut-être en groupe près des rivières',
    fait: 'Son museau avait 120 dents pointues pour attraper des poissons slippery ! Son nom veut dire "imitateur de crocodile" !',
    desc: 'Le Suchomimus était un dinosaure-crocodile ! Il avait un long museau avec des tas de dents pointues pour attraper des énormes poissons dans les rivières africaines.',
    png: 'Suchomimus.png',
    color: '#1a6a8a',
    continent: 'Afrique',
    periode: 'cretace',
  },
  {
    id: 'baryonyx',
    famille: 'volant',
    name: 'Baryonyx',
    full: 'Baryonyx walkeri',
    cat: 'piscivores',
    epoque: 'Crétacé · il y a 125 millions d\'ans',
    region: 'Europe (Angleterre)',
    taille_m: 9,
    hauteur_m: 2.5,
    poids_t: 1.7,
    comp_taille: _compLong(9),
    comp_hauteur: _compHaut(2.5),
    comp_poids: _compPoids(1.7),
    nom_etym: 'Son nom veut dire «griffe lourde» en grec — il avait une énorme griffe de 30 centimètres !',
    regime: '🐟 Piscivore',
    superpower: 'Une énorme griffe sur le pouce — 31 cm ! Pour harponner les poissons !',
    chasseurs: 'Grands carnivores européens',
    proies: 'Poissons, Iguanodon',
    amis: 'Solitaire ou petit groupe',
    fait: 'Découvert par un plombier en Angleterre ! On a trouvé dans son estomac des écailles de poisson ET des os d\'Iguanodon !',
    desc: 'Le Baryonyx avait une énorme griffe pour attraper les poissons, comme un ours pêcheur ! Découvert en Angleterre, on a trouvé du poisson dans son estomac. Un vrai pêcheur géant !',
    png: 'Baryonyx.png',
    color: '#2874a6',
    continent: 'Europe',
    periode: 'cretace',
  },
  {
    id: 'therizinosaurus',
    famille: 'bizarre',
    name: 'Therizinosaurus',
    full: 'Therizinosaurus cheloniformis',
    cat: 'herbivores',
    epoque: 'Crétacé · il y a 70 millions d\'ans',
    region: 'Asie (Mongolie)',
    taille_m: 10,
    hauteur_m: 5,
    poids_t: 5,
    comp_taille: _compLong(10),
    comp_hauteur: _compHaut(5),
    comp_poids: _compPoids(5),
    nom_etym: 'Son nom veut dire «lézard à faux» en grec — ses griffes étaient aussi longues et courbées qu\'une faux !',
    regime: '🌿 Herbivore',
    superpower: 'Les griffes les plus LONGUES de tous les animaux — 1 mètre ! Mais mangeait des plantes !',
    chasseurs: 'Tarbosaure — mais les griffes repoussaient !',
    proies: 'Mange des plantes',
    amis: 'Solitaire',
    fait: 'Il avait des griffes d\'1 mètre de long — les plus longues de tous les animaux ! Et pourtant il mangeait des feuilles et des plantes paisiblement !',
    desc: 'Le Therizinosaurus avait les griffes les plus longues de toute l\'histoire des animaux — 1 mètre chacune ! Mais malgré ces griffes impressionnantes, il ne mangeait que des plantes et des feuilles !',
    png: 'Therizinosaurus.png',
    color: '#117864',
    continent: 'Asie',
    periode: 'cretace',
  },
  {
    id: 'dimetrodon',
    famille: 'bizarre',
    name: 'Dimétrodon',
    full: 'Dimetrodon grandis',
    cat: 'volants_marins',
    epoque: 'Permien · il y a 280 millions d\'ans (avant les dinos !)',
    region: 'Amérique du Nord',
    taille_m: 3.5,
    hauteur_m: 1.8,
    poids_t: 0.25,
    comp_taille: _compLong(3.5),
    comp_hauteur: _compHaut(1.8),
    comp_poids: _compPoids(0.25),
    nom_etym: 'Son nom veut dire «deux tailles de dents» en grec — il avait des dents courtes et des dents longues en même temps !',
    regime: '🥩 Carnivore',
    superpower: 'Une grande voile pour se réchauffer au soleil — le thermomètre vivant !',
    chasseurs: 'Autres prédateurs du Permien',
    proies: 'Petits reptiles',
    amis: 'Solitaire',
    fait: 'Attention : le Dimétrodon N\'EST PAS un dinosaure ! Il vivait 50 millions d\'ans AVANT eux et est en fait plus proche de nous (les mammifères) que des dinos !',
    desc: 'Le Dimétrodon n\'est pas un dinosaure — c\'est un ancêtre des mammifères ! Il vivait bien avant les dinos. Sa grande voile sur le dos lui servait à se réchauffer au soleil.',
    png: 'Dimetrodon.png',
    color: '#0e6655',
    continent: 'Amérique du Nord',
    periode: 'permien',
  },
];
