// ─── Encyclopédie Dinosaures MaxPlay ───
// 50 dinos · données riches · FR · adapté 3-5 ans
// Catégories : chasseurs · herbivores · blindes · cretes_cornus · rapaces · airs_mers

const DINO_CATEGORIES = [
  { id: 'chasseurs',     label: 'Les Chasseurs',       emoji: '🦷', color: '#c0392b', bg: 'linear-gradient(135deg,#7b0000,#c0392b)' },
  { id: 'herbivores',    label: 'Géants Herbivores',   emoji: '🌿', color: '#27ae60', bg: 'linear-gradient(135deg,#0a4a1e,#27ae60)' },
  { id: 'blindes',       label: 'Les Tout Blindés',    emoji: '🛡️', color: '#7f8c8d', bg: 'linear-gradient(135deg,#2c3e50,#7f8c8d)' },
  { id: 'cretes_cornus', label: 'Crestés & Cornus',    emoji: '🎶', color: '#8e44ad', bg: 'linear-gradient(135deg,#4a0080,#8e44ad)' },
  { id: 'rapaces',       label: 'Rapaces Malins',      emoji: '⚡', color: '#e67e22', bg: 'linear-gradient(135deg,#7a3000,#e67e22)' },
  { id: 'airs_mers',     label: 'Airs, Mers & Biz.',  emoji: '🌊', color: '#2980b9', bg: 'linear-gradient(135deg,#003366,#2980b9)' },
];

const DINOS = [

  // ══════════════ 1. LES CHASSEURS ══════════════

  {
    id: 'tyrannosaurus',
    name: 'T-Rex',
    full: 'Tyrannosaurus Rex',
    cat: 'chasseurs',
    epoque: 'Crétacé · il y a 66 millions d\'ans',
    region: 'Amérique du Nord',
    taille_m: 12,
    poids_t: 8,
    comp_taille: 'aussi long que 2 bus scolaires !',
    comp_poids: 'aussi lourd que 8 hippopotames !',
    regime: '🥩 Carnivore',
    superpower: 'La morsure la plus puissante de tous les dinos terrestres !',
    chasseurs: 'Personne n\'osait l\'attaquer... il était le roi !',
    proies: 'Triceratops, Edmontosaurus, Ankylosaure',
    amis: 'Plutôt solitaire, mais peut-être en famille parfois',
    fait: 'Ses dents mesuraient 20 cm — plus longues que ta main ! Et il en avait 60 !',
    desc: 'Le T-Rex est le roi des dinosaures. Il avait une tête énorme, des dents géantes, et des bras tout petits. Mais attention, ses pattes arrière couraient très vite !',
    png: 'Tyrannosaurus.png',
    color: '#c0392b',
  },
  {
    id: 'spinosaurus',
    name: 'Spinosaure',
    full: 'Spinosaurus aegyptiacus',
    cat: 'chasseurs',
    epoque: 'Crétacé · il y a 95 millions d\'ans',
    region: 'Afrique du Nord',
    taille_m: 15,
    poids_t: 9,
    comp_taille: 'encore plus long que le T-Rex ! Presque 3 bus !',
    comp_poids: 'aussi lourd que 9 hippopotames !',
    regime: '🐟 Piscivore (mange du poisson !)',
    superpower: 'Nager comme un crocodile géant ! Il adorait l\'eau.',
    chasseurs: 'Personne n\'osait s\'y frotter',
    proies: 'Gros poissons, requins préhistoriques',
    amis: 'Solitaire',
    fait: 'La voile sur son dos pouvait faire 2 mètres de haut — comme une porte d\'entrée !',
    desc: 'Le Spinosaure était encore plus grand que le T-Rex ! Il vivait près des rivières et attrapait d\'énormes poissons. Il avait une grande voile rouge sur le dos.',
    png: 'Spinosaurus.png',
    color: '#2471a3',
  },
  {
    id: 'giganotosaurus',
    name: 'Giganotosaure',
    full: 'Giganotosaurus carolinii',
    cat: 'chasseurs',
    epoque: 'Crétacé · il y a 98 millions d\'ans',
    region: 'Amérique du Sud',
    taille_m: 13,
    poids_t: 8,
    comp_taille: 'aussi long que 2 bus et demi !',
    comp_poids: 'aussi lourd que 8 hippopotames',
    regime: '🥩 Carnivore',
    superpower: 'Chassait en groupe pour attaquer les ÉNORMES sauropodes !',
    chasseurs: 'Aucun prédateur ne l\'attaquait',
    proies: 'Argentinosaurus (le plus grand dino !)',
    amis: 'Chassait peut-être en meutes, comme des lions',
    fait: 'C\'est le plus grand carnivore d\'Amérique du Sud ! Plus grand encore que le T-Rex !',
    desc: 'Le Giganotosaure vivait en Amérique du Sud. Il était ÉNORME et chassait peut-être en groupe pour attraper des dinosaures encore plus grands que lui !',
    png: 'Giganotosaurus.png',
    color: '#a93226',
  },
  {
    id: 'carcharodontosaurus',
    name: 'Carcharodonto.',
    full: 'Carcharodontosaurus saharicus',
    cat: 'chasseurs',
    epoque: 'Crétacé · il y a 95 millions d\'ans',
    region: 'Afrique du Nord',
    taille_m: 13,
    poids_t: 7,
    comp_taille: 'aussi long que 2 bus !',
    comp_poids: 'aussi lourd que 7 hippopotames',
    regime: '🥩 Carnivore',
    superpower: 'Des dents en forme de dents de requin — couper comme un couteau !',
    chasseurs: 'Aucun dans son territoire',
    proies: 'Grands herbivores africains',
    amis: 'Solitaire',
    fait: 'Son nom veut dire "lézard aux dents de requin" ! Ses dents étaient dentelées comme une scie !',
    desc: 'Le Carcharodontosaure vivait en Afrique en même temps que le Spinosaure. Il avait des dents en forme de dents de requin pour découper sa nourriture.',
    png: 'Carcharodontosaurus.png',
    color: '#922b21',
  },
  {
    id: 'acrocanthosaurus',
    name: 'Acrocantho.',
    full: 'Acrocanthosaurus atokensis',
    cat: 'chasseurs',
    epoque: 'Crétacé · il y a 113 millions d\'ans',
    region: 'Amérique du Nord',
    taille_m: 11.5,
    poids_t: 6,
    comp_taille: 'presque aussi long que 2 bus !',
    comp_poids: 'aussi lourd que 6 hippopotames',
    regime: '🥩 Carnivore',
    superpower: 'Une crête de muscles sur tout le dos, comme un bison géant !',
    chasseurs: 'Aucun dans son époque',
    proies: 'Sauropodes géants (Astrodon...)',
    amis: 'Solitaire',
    fait: 'On a trouvé ses empreintes de pas en Texas ! Les traces font 60 cm de long !',
    desc: 'L\'Acrocanthosaure était le T-Rex de son époque. Il avait une grosse bosse de muscles sur le dos et chassait les dinosaures géants.',
    png: 'Acrocanthosaurus.png',
    color: '#8b1a1a',
  },
  {
    id: 'allosaurus',
    name: 'Allosaure',
    full: 'Allosaurus fragilis',
    cat: 'chasseurs',
    epoque: 'Jurassique · il y a 155 millions d\'ans',
    region: 'Amérique du Nord, Europe',
    taille_m: 10,
    poids_t: 2.5,
    comp_taille: 'aussi long qu\'un bus !',
    comp_poids: 'aussi lourd que 2 rhinocéros',
    regime: '🥩 Carnivore',
    superpower: 'Ouvrait sa gueule TRÈS grande comme une hache pour frapper !',
    chasseurs: 'Aucun de son époque n\'osait l\'affronter seul',
    proies: 'Stégosaure, Camarasaure, jeunes sauropodes',
    amis: 'Peut-être en groupe parfois',
    fait: 'Le T-Rex du Jurassique ! On a trouvé des centaines de ses os dans un seul endroit !',
    desc: 'L\'Allosaure était le super chasseur du Jurassique. Il ouvrait sa mâchoire très grande pour frapper sa proie comme un coup de hache !',
    png: 'Allosaurus.png',
    color: '#b03a2e',
  },
  {
    id: 'tarbosaurus',
    name: 'Tarbosaure',
    full: 'Tarbosaurus bataar',
    cat: 'chasseurs',
    epoque: 'Crétacé · il y a 70 millions d\'ans',
    region: 'Asie (Mongolie)',
    taille_m: 10,
    poids_t: 5,
    comp_taille: 'aussi long qu\'un bus !',
    comp_poids: 'aussi lourd que 5 hippopotames',
    regime: '🥩 Carnivore',
    superpower: 'Le T-Rex d\'Asie — cousin direct !',
    chasseurs: 'Aucun dans son territoire',
    proies: 'Grands herbivores d\'Asie',
    amis: 'Solitaire',
    fait: 'C\'est le cousin asiatique du T-Rex ! Il vivait dans le désert de Gobi en Mongolie.',
    desc: 'Le Tarbosaure était le T-Rex de l\'Asie ! Il vivait dans les déserts de Mongolie et ressemblait beaucoup à son cousin américain.',
    png: 'Tarbosaurus.png',
    color: '#96281b',
  },
  {
    id: 'albertosaurus',
    name: 'Albertosaure',
    full: 'Albertosaurus sarcophagus',
    cat: 'chasseurs',
    epoque: 'Crétacé · il y a 70 millions d\'ans',
    region: 'Canada',
    taille_m: 9,
    poids_t: 2,
    comp_taille: 'presque aussi long qu\'un bus',
    comp_poids: 'aussi lourd que 2 rhinocéros',
    regime: '🥩 Carnivore',
    superpower: 'Chassait peut-être en meute ! Le loup des T-Rex !',
    chasseurs: 'Aucun de son époque',
    proies: 'Hadrosaures, cératopsiens',
    amis: 'Vivait peut-être en groupe — on a trouvé 26 squelettes ensemble !',
    fait: 'On a trouvé 26 Albertosaures ensemble au Canada ! Ils chassaient peut-être en groupe comme des loups !',
    desc: 'L\'Albertosaure était plus petit que le T-Rex mais il était très malin. Il chassait peut-être en groupe comme les loups d\'aujourd\'hui !',
    png: 'Albertosaurus.png',
    color: '#922b21',
  },
  {
    id: 'gorgosaurus',
    name: 'Gorgosaure',
    full: 'Gorgosaurus libratus',
    cat: 'chasseurs',
    epoque: 'Crétacé · il y a 76 millions d\'ans',
    region: 'Canada',
    taille_m: 9,
    poids_t: 2.5,
    comp_taille: 'presque aussi long qu\'un bus',
    comp_poids: 'aussi lourd que 2 rhinocéros',
    regime: '🥩 Carnivore',
    superpower: 'Très rapide pour sa taille !',
    chasseurs: 'Aucun prédateur dans son territoire',
    proies: 'Hadrosaures, parasaurolophus',
    amis: 'Solitaire',
    fait: 'Le cousin canadien du T-Rex ! Il vivait avec les Parasaurolophus et les Ankylosaures.',
    desc: 'Le Gorgosaure était un grand chasseur du Canada il y a très longtemps. Il courait vite et avait des dents très tranchantes.',
    png: 'Gorgosaurus.png',
    color: '#a83232',
  },
  {
    id: 'ceratosaurus',
    name: 'Cératosaure',
    full: 'Ceratosaurus nasicornis',
    cat: 'chasseurs',
    epoque: 'Jurassique · il y a 150 millions d\'ans',
    region: 'Amérique du Nord, Afrique',
    taille_m: 6,
    poids_t: 0.5,
    comp_taille: 'aussi long qu\'une voiture et demie',
    comp_poids: 'aussi lourd qu\'un cheval',
    regime: '🥩 Carnivore',
    superpower: 'Il avait UNE corne sur le nez — unique chez les grands carnivores !',
    chasseurs: 'Allosaure pouvait l\'affronter',
    proies: 'Petits dinosaures, poissons',
    amis: 'Solitaire',
    fait: 'Il avait des petites cornes sur la tête et une grande corne sur le nez — le seul grand carnivore avec une corne !',
    desc: 'Le Cératosaure avait quelque chose de spécial : une corne sur le nez ! Il vivait au Jurassique et chassait de petits animaux et des poissons.',
    png: 'Ceratosaurus.png',
    color: '#a04020',
  },
  {
    id: 'dilophosaurus',
    name: 'Dilophosaure',
    full: 'Dilophosaurus wetherilli',
    cat: 'chasseurs',
    epoque: 'Jurassique · il y a 193 millions d\'ans',
    region: 'Amérique du Nord',
    taille_m: 6,
    poids_t: 0.4,
    comp_taille: 'aussi long qu\'une voiture',
    comp_poids: 'aussi lourd qu\'un poney',
    regime: '🥩 Carnivore',
    superpower: '2 crêtes colorées sur la tête comme un chapeau de fête !',
    chasseurs: 'Prédateurs plus grands',
    proies: 'Petits dinos, charognes',
    amis: 'Peut-être en groupe',
    fait: 'Il avait 2 crêtes parallèles sur la tête — elles étaient probablement très colorées pour attirer les amis !',
    desc: 'Le Dilophosaure avait deux belles crêtes colorées sur la tête. C\'est un des premiers grands dinosaures carnivores !',
    png: 'Dilophosaurus.png',
    color: '#b05a00',
  },
  {
    id: 'carnotaurus',
    name: 'Carnotaure',
    full: 'Carnotaurus sastrei',
    cat: 'chasseurs',
    epoque: 'Crétacé · il y a 72 millions d\'ans',
    region: 'Amérique du Sud',
    taille_m: 8,
    poids_t: 1.5,
    comp_taille: 'aussi long qu\'un grand bus',
    comp_poids: 'aussi lourd qu\'un rhinocéros',
    regime: '🥩 Carnivore',
    superpower: 'Le chasseur le PLUS RAPIDE parmi les grands carnivores — jusqu\'à 56 km/h !',
    chasseurs: 'Aucun dans son territoire',
    proies: 'Hadrosaures, dinosaures moyens',
    amis: 'Solitaire',
    fait: 'Il avait DE VRAIES CORNES au-dessus des yeux — comme un taureau ! Et il était ultra-rapide !',
    desc: 'Le Carnotaure avait des cornes comme un taureau et courait très très vite ! C\'est un des dinos les plus rapides de toute son époque.',
    png: 'Carnotaurus.png',
    color: '#7d3c00',
  },
  {
    id: 'cryolophosaurus',
    name: 'Cryolophosaure',
    full: 'Cryolophosaurus ellioti',
    cat: 'chasseurs',
    epoque: 'Jurassique · il y a 194 millions d\'ans',
    region: 'Antarctique !',
    taille_m: 6.5,
    poids_t: 0.5,
    comp_taille: 'aussi long qu\'une voiture',
    comp_poids: 'aussi lourd qu\'un cheval',
    regime: '🥩 Carnivore',
    superpower: 'Vivait en Antarctique ! Le dino des neiges !',
    chasseurs: 'Prédateurs plus grands',
    proies: 'Herbivores de l\'Antarctique',
    amis: 'Inconnu',
    fait: 'Découvert en Antarctique ! Il vivait là quand c\'était encore chaud. Et il avait une crête bizarre peignée vers l\'avant — surnommé "Elvisaurus" !',
    desc: 'Le Cryolophosaure vivait en Antarctique quand il faisait encore un peu chaud là-bas ! Il avait une crête rigolote et on l\'appelle parfois Elvisaurus !',
    png: 'Cryolophosaurus.png',
    color: '#1a5276',
  },

  // ══════════════ 2. GÉANTS HERBIVORES ══════════════

  {
    id: 'brachiosaurus',
    name: 'Brachiosaure',
    full: 'Brachiosaurus altithorax',
    cat: 'herbivores',
    epoque: 'Jurassique · il y a 150 millions d\'ans',
    region: 'Amérique du Nord, Afrique',
    taille_m: 26,
    poids_t: 60,
    comp_taille: 'aussi long que 4 bus ! Et aussi HAUT qu\'un immeuble de 4 étages !',
    comp_poids: 'aussi lourd que 60 hippopotames — ou 10 éléphants !',
    regime: '🌿 Herbivore',
    superpower: 'Mangeait les feuilles tout en haut des arbres que les autres ne pouvaient pas atteindre !',
    chasseurs: 'Seulement les très grands carnivores osaient attaquer les jeunes',
    proies: 'Mange des plantes',
    amis: 'Vivait en troupeau — plus fort ensemble !',
    fait: 'Sa tête était à 13 mètres de haut — aussi haut qu\'une maison ! Pour avaler, il avalait des pierres pour broyer sa nourriture dans son estomac.',
    desc: 'Le Brachiosaure était immense ! Il mangeait les feuilles tout en haut des arbres. Il avait un très long cou et de grandes pattes avant. Un géant gentil !',
    png: 'Brachiosaurus.png',
    color: '#1e8449',
  },
  {
    id: 'diplodocus',
    name: 'Diplodocus',
    full: 'Diplodocus longus',
    cat: 'herbivores',
    epoque: 'Jurassique · il y a 150 millions d\'ans',
    region: 'Amérique du Nord',
    taille_m: 27,
    poids_t: 15,
    comp_taille: 'aussi long que 4 bus et demi !',
    comp_poids: 'aussi lourd que 15 hippopotames',
    regime: '🌿 Herbivore',
    superpower: 'Sa queue claquait comme un fouet — BOOM ! — pour faire peur aux chasseurs !',
    chasseurs: 'Allosaure, Ceratosaure pour les jeunes',
    proies: 'Mange des plantes',
    amis: 'En grand troupeau',
    fait: 'Sa queue faisait un BOOM supersonique en claquant ! Plus fort qu\'une explosion !',
    desc: 'Le Diplodocus était l\'un des plus longs dinosaures. Il avait un très long cou ET une très longue queue. Cette queue faisait un énorme bruit de fouet pour effrayer les chasseurs !',
    png: 'Diplodocus.png',
    color: '#239b56',
  },
  {
    id: 'apatosaurus',
    name: 'Apatosaure',
    full: 'Apatosaurus louisae',
    cat: 'herbivores',
    epoque: 'Jurassique · il y a 150 millions d\'ans',
    region: 'Amérique du Nord',
    taille_m: 22,
    poids_t: 25,
    comp_taille: 'aussi long que 3 bus et demi !',
    comp_poids: 'aussi lourd que 25 hippopotames !',
    regime: '🌿 Herbivore',
    superpower: 'Un cou de 6 mètres pour manger des feuilles très haut !',
    chasseurs: 'Allosaure pour les jeunes',
    proies: 'Mange des plantes',
    amis: 'En troupeau',
    fait: 'Pendant longtemps, on l\'appelait "Brontosaure" — mais son vrai nom c\'est Apatosaure ! Il mangeait 250 kg de plantes PAR JOUR !',
    desc: 'L\'Apatosaure est le géant gentil que beaucoup appellent Brontosaure. Il mangeait autant de plantes en un jour que toi en une année !',
    png: 'Apatosaurus.png',
    color: '#196f3d',
  },
  {
    id: 'camarasaurus',
    name: 'Camarasaure',
    full: 'Camarasaurus lentus',
    cat: 'herbivores',
    epoque: 'Jurassique · il y a 155 millions d\'ans',
    region: 'Amérique du Nord',
    taille_m: 18,
    poids_t: 18,
    comp_taille: 'aussi long que 3 bus !',
    comp_poids: 'aussi lourd que 18 hippopotames',
    regime: '🌿 Herbivore',
    superpower: 'Des dents épaisses pour mâcher des branches très dures !',
    chasseurs: 'Allosaure pour les jeunes',
    proies: 'Mange des plantes',
    amis: 'En troupeau avec ses petits',
    fait: 'Le sauropode le plus commun d\'Amérique du Nord ! Il avait de grandes fenêtres dans son crâne pour alléger sa tête.',
    desc: 'Le Camarasaure était un dinosaure géant avec une grosse tête et de fortes dents. Il vivait en troupeau et s\'occupait bien de ses bébés.',
    png: 'Camarasaurus.png',
    color: '#17a589',
  },
  {
    id: 'amargasaurus',
    name: 'Amargasaure',
    full: 'Amargasaurus cazaui',
    cat: 'herbivores',
    epoque: 'Crétacé · il y a 125 millions d\'ans',
    region: 'Amérique du Sud',
    taille_m: 10,
    poids_t: 3,
    comp_taille: 'aussi long qu\'un bus',
    comp_poids: 'aussi lourd que 3 rhinocéros',
    regime: '🌿 Herbivore',
    superpower: '2 rangées d\'épines sur le cou ! Pour se défendre ou attirer des amis !',
    chasseurs: 'Grands carnivores d\'Amérique du Sud',
    proies: 'Mange des plantes',
    amis: 'En petit groupe',
    fait: 'Il avait 2 rangées d\'épines IMMENSES sur le cou et le dos ! Comme un haie d\'épines vivante !',
    desc: 'L\'Amargasaure avait 2 rangées de grandes épines sur le cou et le dos. C\'était peut-être pour se défendre ou pour montrer à ses amis qu\'il était beau !',
    png: 'Amargasaurus.png',
    color: '#0e6655',
  },
  {
    id: 'plateosaurus',
    name: 'Plateosaure',
    full: 'Plateosaurus engelhardti',
    cat: 'herbivores',
    epoque: 'Trias · il y a 210 millions d\'ans',
    region: 'Europe',
    taille_m: 8,
    poids_t: 4,
    comp_taille: 'aussi long qu\'un grand bus',
    comp_poids: 'aussi lourd que 4 rhinocéros',
    regime: '🌿 Herbivore',
    superpower: 'L\'un des PREMIERS grands dinosaures herbivores — le pionnier !',
    chasseurs: 'Premiers grands carnivores du Trias',
    proies: 'Mange des plantes',
    amis: 'En troupeau',
    fait: 'Un des premiers grands dinos ! Il marchait sur 4 pattes mais pouvait se dresser sur 2 pour atteindre les hautes branches.',
    desc: 'Le Plateosaure était l\'un des premiers grands dinosaures. Il vivait au Trias, longtemps avant le T-Rex. Il pouvait se lever sur ses pattes arrière pour manger plus haut !',
    png: 'Plateosaurus.png',
    color: '#148f77',
  },

  // ══════════════ 3. LES TOUT BLINDÉS ══════════════

  {
    id: 'ankylosaurus',
    name: 'Ankylosaure',
    full: 'Ankylosaurus magniventris',
    cat: 'blindes',
    epoque: 'Crétacé · il y a 66 millions d\'ans',
    region: 'Amérique du Nord',
    taille_m: 10,
    poids_t: 8,
    comp_taille: 'aussi long qu\'un bus',
    comp_poids: 'aussi lourd que 8 hippopotames',
    regime: '🌿 Herbivore',
    superpower: 'Son dos était une armure de plaques osseuses + une queue-massue pour casser les os du T-Rex !',
    chasseurs: 'T-Rex essayait ! Mais c\'était très dur...',
    proies: 'Mange des plantes',
    amis: 'Solitaire ou petit groupe',
    fait: 'Sa queue-massue pouvait briser les os du T-Rex ! Même l\'os le plus solide !',
    desc: 'L\'Ankylosaure était le char d\'assaut des dinosaures ! Son dos était recouvert d\'une armure dure comme de la roche. Et sa queue finissait par une grosse boule qui cassait tout !',
    png: 'Ankylosaurus.png',
    color: '#626567',
  },
  {
    id: 'euoplocephalus',
    name: 'Euoplocéphale',
    full: 'Euoplocephalus tutus',
    cat: 'blindes',
    epoque: 'Crétacé · il y a 75 millions d\'ans',
    region: 'Canada',
    taille_m: 6,
    poids_t: 2.5,
    comp_taille: 'aussi long qu\'une grande voiture',
    comp_poids: 'aussi lourd que 2 rhinocéros',
    regime: '🌿 Herbivore',
    superpower: 'Même ses paupières étaient blindées ! Rien ne pouvait le blesser !',
    chasseurs: 'Gorgosaure tentait l\'attaque',
    proies: 'Mange des plantes',
    amis: 'Solitaire',
    fait: 'Même SES YEUX avaient une armure osseuse ! Le dino le mieux protégé de toute l\'histoire !',
    desc: 'L\'Euoplocéphale était encore plus blindé que l\'Ankylosaure. Même ses paupières étaient faites d\'os ! Il avait aussi une queue-massue super puissante.',
    png: 'Euoplocephalus.png',
    color: '#717d7e',
  },
  {
    id: 'stegosaurus',
    name: 'Stégosaure',
    full: 'Stegosaurus ungulatus',
    cat: 'blindes',
    epoque: 'Jurassique · il y a 155 millions d\'ans',
    region: 'Amérique du Nord, Europe',
    taille_m: 9,
    poids_t: 4,
    comp_taille: 'aussi long qu\'un bus mais plus bas',
    comp_poids: 'aussi lourd que 4 rhinocéros',
    regime: '🌿 Herbivore',
    superpower: 'Les grandes plaques sur son dos régulaient sa température comme un radiateur !',
    chasseurs: 'Allosaure — mais attention à la queue !',
    proies: 'Mange des plantes',
    amis: 'Peut-être en petit groupe',
    fait: 'Son cerveau était de la taille d\'une noix de noix ! Mais sa queue avec 4 piques pouvait percer l\'Allosaure !',
    desc: 'Le Stégosaure avait de grandes plaques colorées sur le dos et 4 longues piques au bout de la queue. Ses plaques lui servaient peut-être de radiateur pour se réchauffer ou se refroidir !',
    png: 'Stegosaurus.png',
    color: '#5d6d7e',
  },
  {
    id: 'kentrosaurus',
    name: 'Kéntrosaure',
    full: 'Kentrosaurus aethiopicus',
    cat: 'blindes',
    epoque: 'Jurassique · il y a 155 millions d\'ans',
    region: 'Afrique (Tanzanie)',
    taille_m: 4.5,
    poids_t: 1,
    comp_taille: 'aussi long qu\'une grande voiture',
    comp_poids: 'aussi lourd qu\'un hippopotame',
    regime: '🌿 Herbivore',
    superpower: 'Des piques partout sur le dos ET sur les épaules — une forêt d\'épines !',
    chasseurs: 'Carnivores africains',
    proies: 'Mange des plantes',
    amis: 'Peut-être en troupeau',
    fait: 'Le cousin africain du Stégosaure ! Il avait encore plus de piques — jusqu\'aux épaules ! Même les carnivores évitaient de l\'attaquer par derrière.',
    desc: 'Le Kéntrosaure était le cousin africain du Stégosaure. Il était plus petit mais avait encore plus de piques sur tout le corps. Même sur les épaules !',
    png: 'Kentrosaurus.png',
    color: '#4d5656',
  },

  // ══════════════ 4. CRESTÉS & CORNUS ══════════════

  {
    id: 'triceratops',
    name: 'Tricératops',
    full: 'Triceratops horridus',
    cat: 'cretes_cornus',
    epoque: 'Crétacé · il y a 66 millions d\'ans',
    region: 'Amérique du Nord',
    taille_m: 9,
    poids_t: 12,
    comp_taille: 'aussi long qu\'un bus',
    comp_poids: 'aussi lourd que 2 éléphants !',
    regime: '🌿 Herbivore',
    superpower: '3 cornes et une collerette osseuse géante — le bouclier parfait contre le T-Rex !',
    chasseurs: 'T-Rex — mais le Tricératops se défendait bien !',
    proies: 'Mange des plantes',
    amis: 'Peut-être en troupeau pour protéger les petits',
    fait: 'Ses cornes faisaient 1 mètre de long ! Et on a trouvé des os de T-Rex avec des marques de cornes de Tricératops — ils se battaient vraiment !',
    desc: 'Le Tricératops avait 3 cornes et un grand bouclier osseux autour de la tête. Il n\'avait pas peur du T-Rex ! C\'était le grand guerrier des herbivores.',
    png: 'Triceratops.png',
    color: '#7d6608',
  },
  {
    id: 'styracosaurus',
    name: 'Styracosaure',
    full: 'Styracosaurus albertensis',
    cat: 'cretes_cornus',
    epoque: 'Crétacé · il y a 75 millions d\'ans',
    region: 'Canada',
    taille_m: 5.5,
    poids_t: 3,
    comp_taille: 'aussi long qu\'une grande voiture',
    comp_poids: 'aussi lourd que 3 rhinocéros',
    regime: '🌿 Herbivore',
    superpower: 'Une couronne de 6 grandes cornes autour de la collerette — le dino le plus décoré !',
    chasseurs: 'Gorgosaure, Albertosaure',
    proies: 'Mange des plantes',
    amis: 'En grand troupeau — on a trouvé des centaines ensemble !',
    fait: 'Sa collerette avait 6 grandes cornes ! C\'était peut-être pour attirer des amis ou faire peur aux ennemis.',
    desc: 'Le Styracosaure avait une magnifique couronne de cornes autour de la tête. Il vivait en grand troupeau pour se protéger des grands carnivores.',
    png: 'Styracosaurus.png',
    color: '#9a7d0a',
  },
  {
    id: 'protoceratops',
    name: 'Protocératops',
    full: 'Protoceratops andrewsi',
    cat: 'cretes_cornus',
    epoque: 'Crétacé · il y a 75 millions d\'ans',
    region: 'Asie (Mongolie)',
    taille_m: 1.8,
    poids_t: 0.18,
    comp_taille: 'aussi long qu\'un grand chien',
    comp_poids: 'aussi lourd qu\'un grand chien',
    regime: '🌿 Herbivore',
    superpower: 'Le grand-père de tous les dinos à cornes ! Et une mâchoire très puissante.',
    chasseurs: 'Vélociraptor — et ils se battaient !',
    proies: 'Mange des plantes',
    amis: 'En troupeau avec des nids en groupe',
    fait: 'On a trouvé un fossile incroyable : un Vélociraptor et un Protocératops morts en train de se battre ! Ensevelis par une tempête de sable !',
    desc: 'Le Protocératops était le petit ancêtre des Tricératops. Il avait déjà une collerette mais pas encore de cornes. Et il se battait courageusement contre les Vélociraptors !',
    png: 'Protoceratops.png',
    color: '#b7950b',
  },
  {
    id: 'psittacosaurus',
    name: 'Psittacosaure',
    full: 'Psittacosaurus mongoliensis',
    cat: 'cretes_cornus',
    epoque: 'Crétacé · il y a 120 millions d\'ans',
    region: 'Asie',
    taille_m: 1.5,
    poids_t: 0.02,
    comp_taille: 'aussi long qu\'un chien',
    comp_poids: 'aussi lourd qu\'un chat',
    regime: '🌿 Herbivore',
    superpower: 'Un bec de perroquet pour couper les plantes ! Et des plumes sur la queue !',
    chasseurs: 'Petits et grands carnivores d\'Asie',
    proies: 'Mange des plantes',
    amis: 'En groupe, les adultes gardaient les petits',
    fait: 'Un fossile montre un adulte avec 34 petits ! Il faisait la nounou pour toute la famille !',
    desc: 'Le Psittacosaure avait un bec comme un perroquet et de jolies plumes sur la queue. C\'est l\'ancêtre du Tricératops. Et les adultes gardaient les bébés comme une vraie école !',
    png: 'Psittacosaurus.png',
    color: '#9b7e04',
  },
  {
    id: 'parasaurolophus',
    name: 'Parasaurolophus',
    full: 'Parasaurolophus walkeri',
    cat: 'cretes_cornus',
    epoque: 'Crétacé · il y a 76 millions d\'ans',
    region: 'Amérique du Nord',
    taille_m: 10,
    poids_t: 2.5,
    comp_taille: 'aussi long qu\'un bus',
    comp_poids: 'aussi lourd que 2 rhinocéros',
    regime: '🌿 Herbivore',
    superpower: 'Sa crête était un instrument de musique ! Il soufflait dedans pour faire des sons très forts !',
    chasseurs: 'T-Rex, Gorgosaure',
    proies: 'Mange des plantes',
    amis: 'En grand troupeau — les cris avertissaient le groupe du danger !',
    fait: 'Sa crête creuse faisait des sons comme un trombone ! On peut reconstruire sa musique en ordinateur !',
    desc: 'Le Parasaurolophus avait une grande crête creuse sur la tête. Il soufflait de l\'air dedans pour faire des sons très forts — comme un grand klaxon — pour parler avec son troupeau !',
    png: 'Parasaurolophus.png',
    color: '#6e2f8a',
  },
  {
    id: 'corythosaurus',
    name: 'Corythosaure',
    full: 'Corythosaurus casuarius',
    cat: 'cretes_cornus',
    epoque: 'Crétacé · il y a 77 millions d\'ans',
    region: 'Canada',
    taille_m: 9,
    poids_t: 4,
    comp_taille: 'aussi long qu\'un bus',
    comp_poids: 'aussi lourd que 4 rhinocéros',
    regime: '🌿 Herbivore',
    superpower: 'Sa crête en forme de casque servait de klaxon ET de radiateur !',
    chasseurs: 'T-Rex, Gorgosaure',
    proies: 'Mange des plantes',
    amis: 'En grand troupeau',
    fait: 'Sa crête ressemblait au casque d\'un soldat grec ! Elle était probablement très colorée pour reconnaître les membres de sa famille.',
    desc: 'Le Corythosaure portait une grande crête en forme de casque sur la tête. Cette crête lui servait à faire des sons pour parler avec ses amis du troupeau.',
    png: 'Corythosaurus.png',
    color: '#7d3c98',
  },
  {
    id: 'edmontosaurus',
    name: 'Edmontosaure',
    full: 'Edmontosaurus regalis',
    cat: 'cretes_cornus',
    epoque: 'Crétacé · il y a 68 millions d\'ans',
    region: 'Amérique du Nord',
    taille_m: 12,
    poids_t: 4,
    comp_taille: 'aussi long que 2 bus !',
    comp_poids: 'aussi lourd que 4 rhinocéros',
    regime: '🌿 Herbivore',
    superpower: 'Des centaines de dents pour mâcher — jamais à court de dents de rechange !',
    chasseurs: 'T-Rex — sa proie préférée !',
    proies: 'Mange des plantes',
    amis: 'En très grand troupeau — des milliers ensemble !',
    fait: 'Il avait jusqu\'à 1000 petites dents qui se remplaçaient sans cesse ! Quand une tombait, une nouvelle poussait.',
    desc: 'L\'Edmontosaure était un grand dino à bec de canard. Il vivait en immenses troupeaux et avait des centaines de dents pour broyer les plantes les plus dures !',
    png: 'Edmontosaurus.png',
    color: '#8e44ad',
  },
  {
    id: 'maiasaura',
    name: 'Maiasaura',
    full: 'Maiasaura peeblesorum',
    cat: 'cretes_cornus',
    epoque: 'Crétacé · il y a 77 millions d\'ans',
    region: 'Amérique du Nord',
    taille_m: 9,
    poids_t: 3,
    comp_taille: 'aussi long qu\'un bus',
    comp_poids: 'aussi lourd que 3 rhinocéros',
    regime: '🌿 Herbivore',
    superpower: 'La meilleure maman dinosaure ! Elle nourrissait ses bébés dans le nid pendant des mois !',
    chasseurs: 'T-Rex, grands carnivores',
    proies: 'Mange des plantes',
    amis: 'En colonies avec des centaines de nids ensemble — comme un village !',
    fait: 'Son nom veut dire "bonne maman lézard" ! On a trouvé ses nids avec des œufs et des bébés — elle les nourrissait dans le nid !',
    desc: 'La Maiasaura était la meilleure maman de tous les dinosaures ! Elle construisait des nids, pondait des œufs, et nourrissait ses bébés pendant longtemps. Elle vivait en grand village avec d\'autres familles !',
    png: 'Maiasaura.png',
    color: '#9b59b6',
  },
  {
    id: 'iguanodon',
    name: 'Iguanodon',
    full: 'Iguanodon bernissartensis',
    cat: 'cretes_cornus',
    epoque: 'Crétacé · il y a 125 millions d\'ans',
    region: 'Europe, Amérique du Nord',
    taille_m: 10,
    poids_t: 3,
    comp_taille: 'aussi long qu\'un bus',
    comp_poids: 'aussi lourd que 3 rhinocéros',
    regime: '🌿 Herbivore',
    superpower: 'Un pique osseux sur le pouce — comme un couteau sur la main !',
    chasseurs: 'Baryonyx, Carnosaures',
    proies: 'Mange des plantes',
    amis: 'En troupeau',
    fait: 'C\'est l\'un des PREMIERS dinosaures découverts en 1820 ! Au début, on croyait que la corne du pouce était sa corne nasale !',
    desc: 'L\'Iguanodon était un dino célèbre car c\'est l\'un des premiers découverts. Il avait un pique tranchant sur le pouce pour se défendre. Il marchait sur 4 pattes mais pouvait se lever sur 2 !',
    png: 'Iguanodon.png',
    color: '#a569bd',
  },
  {
    id: 'pachycephalosaurus',
    name: 'Pachycéphalo.',
    full: 'Pachycephalosaurus wyomingensis',
    cat: 'cretes_cornus',
    epoque: 'Crétacé · il y a 70 millions d\'ans',
    region: 'Amérique du Nord',
    taille_m: 4.5,
    poids_t: 0.45,
    comp_taille: 'aussi long qu\'une grande voiture',
    comp_poids: 'aussi lourd qu\'un cheval',
    regime: '🌿 Herbivore (et peut-être des insectes)',
    superpower: 'Un crâne de 25 cm d\'épaisseur ! Il se battait en se frappant la tête comme les béliers !',
    chasseurs: 'T-Rex, grands carnivores',
    proies: 'Mange des plantes',
    amis: 'En groupe',
    fait: 'Son crâne mesurait 25 cm d\'épaisseur — presque autant que ta tête entière ! Il faisait des joutes comme les béliers !',
    desc: 'Le Pachycephalosaure avait un crâne super épais, comme un casque de moto en os ! Les mâles se battaient en se frappant la tête comme les béliers font aujourd\'hui.',
    png: 'Pachycephalosaurus.png',
    color: '#884ea0',
  },

  // ══════════════ 5. RAPACES MALINS ══════════════

  {
    id: 'velociraptor',
    name: 'Vélociraptor',
    full: 'Velociraptor mongoliensis',
    cat: 'rapaces',
    epoque: 'Crétacé · il y a 75 millions d\'ans',
    region: 'Asie (Mongolie)',
    taille_m: 1.8,
    poids_t: 0.015,
    comp_taille: 'aussi long qu\'un grand chien',
    comp_poids: 'aussi lourd qu\'un grand chat',
    regime: '🥩 Carnivore',
    superpower: 'Ultra-malin, chassait en équipe, et avait une grande griffe rétractable !',
    chasseurs: 'Grands carnivores',
    proies: 'Protocératops, petits dinos',
    amis: 'En meute — le loup des dinos !',
    fait: 'Le vrai Vélociraptor était de la taille d\'un dindon ! Et il avait DES PLUMES ! Rien à voir avec Jurassic Park !',
    desc: 'Le Vélociraptor n\'était pas énorme — de la taille d\'un grand chien. Mais il était couvert de plumes et très très malin ! Il chassait en groupe comme les loups.',
    png: 'Velociraptor.png',
    color: '#d35400',
  },
  {
    id: 'deinonychus',
    name: 'Deinonychus',
    full: 'Deinonychus antirrhopus',
    cat: 'rapaces',
    epoque: 'Crétacé · il y a 115 millions d\'ans',
    region: 'Amérique du Nord',
    taille_m: 3.4,
    poids_t: 0.07,
    comp_taille: 'aussi long qu\'une moto',
    comp_poids: 'aussi lourd qu\'un grand chien',
    regime: '🥩 Carnivore',
    superpower: 'Sa grande griffe de 13 cm était une arme mortelle pour accrocher sa proie !',
    chasseurs: 'Grands carnivores',
    proies: 'Iguanodon, dinos moyens',
    amis: 'En meute de chasseurs',
    fait: 'C\'est le vrai "raptor" de Jurassic Park ! Les Vélociraptors du film ressemblent en fait au Deinonychus !',
    desc: 'Le Deinonychus était le vrai modèle des raptors de Jurassic Park ! Il avait une énorme griffe tranchante et chassait en groupe. Super rapide et super malin !',
    png: 'Deinonychus.png',
    color: '#e67e22',
  },
  {
    id: 'utahraptor',
    name: 'Utahraptor',
    full: 'Utahraptor ostrommaysorum',
    cat: 'rapaces',
    epoque: 'Crétacé · il y a 126 millions d\'ans',
    region: 'Amérique du Nord',
    taille_m: 6,
    poids_t: 0.5,
    comp_taille: 'aussi long qu\'une grande voiture',
    comp_poids: 'aussi lourd qu\'un cheval',
    regime: '🥩 Carnivore',
    superpower: 'La plus grande griffe de tous les raptors — 24 cm ! Un couteau de cuisine géant !',
    chasseurs: 'Aucun de son époque n\'osait l\'attaquer',
    proies: 'Grands herbivores',
    amis: 'Peut-être en meute',
    fait: 'Sa griffe faisait 24 cm — aussi longue que ta main entière ! C\'est le plus grand raptor qui ait jamais existé !',
    desc: 'L\'Utahraptor était un GÉANT parmi les raptors ! Il avait une griffe énorme, courait vite, et était très intelligent. Le super prédateur de son époque !',
    png: 'Utahraptor.png',
    color: '#ca6f1e',
  },
  {
    id: 'microraptor',
    name: 'Microraptor',
    full: 'Microraptor gui',
    cat: 'rapaces',
    epoque: 'Crétacé · il y a 120 millions d\'ans',
    region: 'Chine',
    taille_m: 0.77,
    poids_t: 0.001,
    comp_taille: 'aussi long qu\'un corbeau',
    comp_poids: 'aussi lourd qu\'un oiseau',
    regime: '🥩 Carnivore',
    superpower: '4 ailes ! Planait entre les arbres comme un écureuil volant !',
    chasseurs: 'Autres carnivores, grands reptiles',
    proies: 'Lézards, petits mammifères, poissons',
    amis: 'Solitaire ou petit groupe',
    fait: 'Il avait 4 ailes — 2 sur les bras ET 2 sur les jambes ! Il planait entre les arbres comme un avion miniature !',
    desc: 'Le Microraptor était minuscule avec 4 ailes ! Il planait entre les arbres en Chine pour attraper des lézards et des petits poissons. Incroyable !',
    png: 'Microraptor.png',
    color: '#a04000',
  },
  {
    id: 'troodon',
    name: 'Troodon',
    full: 'Troodon formosus',
    cat: 'rapaces',
    epoque: 'Crétacé · il y a 75 millions d\'ans',
    region: 'Amérique du Nord',
    taille_m: 2,
    poids_t: 0.05,
    comp_taille: 'aussi long qu\'un grand vélo',
    comp_poids: 'aussi lourd qu\'un chat',
    regime: '🥩 Carnivore (et omnivore)',
    superpower: 'Le dinosaure le plus INTELLIGENT ! Le plus grand cerveau par rapport à sa taille !',
    chasseurs: 'Grands carnivores',
    proies: 'Petits mammifères, lézards',
    amis: 'En groupe, peut-être s\'occupait des œufs',
    fait: 'Certains scientifiques pensent que si les dinos n\'avaient pas disparu, le Troodon aurait pu devenir aussi intelligent qu\'un humain en quelques millions d\'années !',
    desc: 'Le Troodon était le dinosaure le plus intelligent de tous ! Il avait de grands yeux pour voir la nuit, de longs bras habiles, et un cerveau énorme. Le professeur des dinosaures !',
    png: 'Troodon.png',
    color: '#b7770d',
  },
  {
    id: 'gallimimus',
    name: 'Gallimimus',
    full: 'Gallimimus bullatus',
    cat: 'rapaces',
    epoque: 'Crétacé · il y a 70 millions d\'ans',
    region: 'Asie (Mongolie)',
    taille_m: 6,
    poids_t: 0.44,
    comp_taille: 'aussi long qu\'une grande voiture',
    comp_poids: 'aussi lourd qu\'un cheval',
    regime: '🌿 Omnivore (mange tout !)',
    superpower: 'Le dino le plus RAPIDE — jusqu\'à 70 km/h ! Plus vite qu\'un cheval au galop !',
    chasseurs: 'T-Rex, grands carnivores',
    proies: 'Petits animaux, œufs, plantes',
    amis: 'En grand troupeau — comme les autruches',
    fait: 'Il courait à 70 km/h — aussi vite qu\'une voiture en ville ! Personne ne pouvait l\'attraper.',
    desc: 'Le Gallimimus était le champion de la vitesse ! Il ressemblait à une grande autruche et courait en grand troupeau. Tellement rapide que même le T-Rex ne pouvait pas l\'attraper !',
    png: 'Gallimimus.png',
    color: '#d4a017',
  },
  {
    id: 'coelophysis',
    name: 'Coelophysis',
    full: 'Coelophysis bauri',
    cat: 'rapaces',
    epoque: 'Trias · il y a 210 millions d\'ans',
    region: 'Amérique du Nord',
    taille_m: 3,
    poids_t: 0.025,
    comp_taille: 'aussi long qu\'un vélo',
    comp_poids: 'aussi lourd qu\'un chat',
    regime: '🥩 Carnivore',
    superpower: 'L\'un des PREMIERS carnivores ! Le grand-père de tous les raptors !',
    chasseurs: 'Premiers grands reptiles du Trias',
    proies: 'Petits lézards, insectes, poissons',
    amis: 'En meute — on a trouvé des centaines ensemble !',
    fait: 'On a trouvé des centaines de squelettes ensemble au Nouveau-Mexique ! Ils se seraient groupés pour survivre à une catastrophe.',
    desc: 'Le Coelophysis était l\'un des tout premiers dinosaures. Petit et rapide, il chassait en meute. C\'est le grand ancêtre de tous les raptors qui viendront bien plus tard !',
    png: 'Coelophysis.png',
    color: '#b7770d',
  },
  {
    id: 'compsognathus',
    name: 'Compsognathus',
    full: 'Compsognathus longipes',
    cat: 'rapaces',
    epoque: 'Jurassique · il y a 150 millions d\'ans',
    region: 'Europe',
    taille_m: 1,
    poids_t: 0.003,
    comp_taille: 'aussi long qu\'un poulet !',
    comp_poids: 'aussi lourd qu\'un poulet !',
    regime: '🥩 Carnivore',
    superpower: 'Le plus PETIT dinosaure connu ! Rapide comme l\'éclair !',
    chasseurs: 'Tous les carnivores',
    proies: 'Lézards, insectes',
    amis: 'Solitaire',
    fait: 'Il était de la taille d\'un poulet ! Pendant longtemps on croyait que c\'était le plus petit dino. Il courait peut-être à 64 km/h !',
    desc: 'Le Compsognathus était minuscule — de la taille d\'un poulet ! Mais il courait très vite pour attraper des lézards et des insectes. Le plus petit chasseur du Jurassique !',
    png: 'Compsognathus.png',
    color: '#c27b00',
  },
  {
    id: 'oviraptor',
    name: 'Oviraptor',
    full: 'Oviraptor philoceratops',
    cat: 'rapaces',
    epoque: 'Crétacé · il y a 75 millions d\'ans',
    region: 'Asie (Mongolie)',
    taille_m: 2,
    poids_t: 0.025,
    comp_taille: 'aussi long qu\'un vélo',
    comp_poids: 'aussi lourd qu\'un chien',
    regime: '🥩 Omnivore (mange tout !)',
    superpower: 'Une crête colorée de perroquet ET un papa poule — il couvait ses œufs !',
    chasseurs: 'Velociraptor, carnivores',
    proies: 'Œufs (peut-être), plantes, petits animaux',
    amis: 'En couple pour élever les petits',
    fait: 'Son nom veut dire "voleur d\'œufs"... mais c\'était un mensonge ! On a découvert qu\'il couvait SES PROPRES œufs comme les oiseaux !',
    desc: 'L\'Oviraptor a été injustement accusé de voler des œufs — en fait il couvait les siens comme un oiseau ! Il avait une belle crête colorée et était un excellent papa !',
    png: 'Oviraptor.png',
    color: '#d68910',
  },

  // ══════════════ 6. AIRS, MERS & BIZARRES ══════════════

  {
    id: 'pteranodon',
    name: 'Ptéranodon',
    full: 'Pteranodon longiceps',
    cat: 'airs_mers',
    epoque: 'Crétacé · il y a 85 millions d\'ans',
    region: 'Amérique du Nord (Kansas)',
    taille_m: 1.8,
    poids_t: 0.025,
    comp_taille: 'envergure de 7 m — aussi large qu\'un avion léger !',
    comp_poids: 'aussi lourd qu\'un grand chien',
    regime: '🐟 Piscivore',
    superpower: 'Volait sans effort en planant sur les courants chauds — le roi des airs !',
    chasseurs: 'Mosasaurus dans l\'eau',
    proies: 'Gros poissons, calmars',
    amis: 'En colonies sur les falaises',
    fait: 'Pas un vrai dino — un reptile volant ! Sa crête orientait son vol comme un gouvernail. Il plongeait pour attraper des poissons.',
    desc: 'Le Ptéranodon n\'était pas un dinosaure mais un reptile volant ! Il avait une envergure énorme et planait sur les vents. Il pêchait en plongeant dans la mer comme un pélican géant !',
    png: 'Pteranodon.png',
    color: '#1a5276',
  },
  {
    id: 'quetzalcoatlus',
    name: 'Quetzalcoatlus',
    full: 'Quetzalcoatlus northropi',
    cat: 'airs_mers',
    epoque: 'Crétacé · il y a 68 millions d\'ans',
    region: 'Amérique du Nord',
    taille_m: 2.5,
    poids_t: 0.2,
    comp_taille: 'envergure de 11 m — aussi large qu\'un avion de ligne !',
    comp_poids: 'aussi lourd qu\'un grand chien',
    regime: '🥩 Carnivore (charognes, petits dinos)',
    superpower: 'Le plus grand animal volant de TOUS LES TEMPS ! Aussi haut qu\'une girafe debout !',
    chasseurs: 'Aucun ne pouvait l\'attraper dans les airs',
    proies: 'Petits dinosaures, charognes',
    amis: 'Solitaire ou petit groupe',
    fait: 'Debout au sol il mesurait 5 mètres de haut — aussi grand qu\'une girafe ! Le plus grand être volant qui ait jamais existé !',
    desc: 'Le Quetzalcoatlus était le plus grand être volant de toute l\'histoire de la Terre ! Debout il était grand comme une girafe. Il volait sur des milliers de kilomètres.',
    png: 'Quetzalcoatlus.png',
    color: '#1f618d',
  },
  {
    id: 'archaeopteryx',
    name: 'Archaeoptéryx',
    full: 'Archaeopteryx lithographica',
    cat: 'airs_mers',
    epoque: 'Jurassique · il y a 150 millions d\'ans',
    region: 'Europe (Allemagne)',
    taille_m: 0.5,
    poids_t: 0.001,
    comp_taille: 'aussi grand qu\'un corbeau',
    comp_poids: 'aussi lourd qu\'un oiseau',
    regime: '🥩 Carnivore',
    superpower: 'Le PREMIER oiseau du monde ! Le chaînon entre dinosaures et oiseaux !',
    chasseurs: 'Prédateurs plus grands',
    proies: 'Insectes, petits lézards',
    amis: 'Solitaire',
    fait: 'C\'est l\'ANCÊTRE DE TOUS LES OISEAUX ! Il avait des plumes ET des dents ET des griffes. Le fossile le plus précieux du monde !',
    desc: 'L\'Archaeoptéryx est l\'ancêtre de tous les oiseaux ! Il avait des plumes comme un oiseau mais aussi des dents et des griffes de dino. C\'est le premier oiseau du monde entier !',
    png: 'Archaeopteryx.png',
    color: '#2e86c1',
  },
  {
    id: 'mosasaurus',
    name: 'Mosasaure',
    full: 'Mosasaurus hoffmannii',
    cat: 'airs_mers',
    epoque: 'Crétacé · il y a 70 millions d\'ans',
    region: 'Toutes les mers du monde',
    taille_m: 17,
    poids_t: 15,
    comp_taille: 'aussi long que 3 bus — dans la mer !',
    comp_poids: 'aussi lourd que 3 baleines bleues immatures',
    regime: '🐟 Carnivore marin',
    superpower: 'Le monstre marin — roi absolu de toutes les mers du Crétacé !',
    chasseurs: 'Aucun — il était au sommet',
    proies: 'Requins, grands poissons, ptérosaures',
    amis: 'Solitaire (territoriau)',
    fait: 'Il attrapait même les ptérosaures en plein vol ! Et il mangeait des requins pour le petit déjeuner !',
    desc: 'Le Mosasaure était le monstre des mers préhistoriques ! Énorme comme un bus géant, il régnait sur tous les océans. Il mangeait même les requins et les ptérosaures !',
    png: 'Mosasaurus.png',
    color: '#154360',
  },
  {
    id: 'suchomimus',
    name: 'Suchomimus',
    full: 'Suchomimus tenerensis',
    cat: 'airs_mers',
    epoque: 'Crétacé · il y a 112 millions d\'ans',
    region: 'Afrique (Niger)',
    taille_m: 11,
    poids_t: 3,
    comp_taille: 'aussi long que presque 2 bus',
    comp_poids: 'aussi lourd que 3 rhinocéros',
    regime: '🐟 Piscivore',
    superpower: 'Un long museau comme un crocodile pour attraper des poissons géants !',
    chasseurs: 'Grands carnivores d\'Afrique',
    proies: 'Poissons géants, crocodiles',
    amis: 'Peut-être en groupe près des rivières',
    fait: 'Son museau avait 120 dents pointues pour attraper des poissons slippery ! Son nom veut dire "imitateur de crocodile" !',
    desc: 'Le Suchomimus était un dinosaure-crocodile ! Il avait un long museau avec des tas de dents pointues pour attraper des énormes poissons dans les rivières africaines.',
    png: 'Suchomimus.png',
    color: '#1a6a8a',
  },
  {
    id: 'baryonyx',
    name: 'Baryonyx',
    full: 'Baryonyx walkeri',
    cat: 'airs_mers',
    epoque: 'Crétacé · il y a 125 millions d\'ans',
    region: 'Europe (Angleterre)',
    taille_m: 9,
    poids_t: 1.7,
    comp_taille: 'aussi long qu\'un grand bus',
    comp_poids: 'aussi lourd qu\'un rhinocéros',
    regime: '🐟 Piscivore',
    superpower: 'Une énorme griffe sur le pouce — 31 cm ! Pour harponner les poissons !',
    chasseurs: 'Grands carnivores européens',
    proies: 'Poissons, Iguanodon',
    amis: 'Solitaire ou petit groupe',
    fait: 'Découvert par un plombier en Angleterre ! On a trouvé dans son estomac des écailles de poisson ET des os d\'Iguanodon !',
    desc: 'Le Baryonyx avait une énorme griffe pour attraper les poissons, comme un ours pêcheur ! Découvert en Angleterre, on a trouvé du poisson dans son estomac. Un vrai pêcheur géant !',
    png: 'Baryonyx.png',
    color: '#2874a6',
  },
  {
    id: 'therizinosaurus',
    name: 'Therizinosaurus',
    full: 'Therizinosaurus cheloniformis',
    cat: 'airs_mers',
    epoque: 'Crétacé · il y a 70 millions d\'ans',
    region: 'Asie (Mongolie)',
    taille_m: 10,
    poids_t: 5,
    comp_taille: 'aussi long qu\'un bus',
    comp_poids: 'aussi lourd que 5 hippopotames',
    regime: '🌿 Herbivore',
    superpower: 'Les griffes les plus LONGUES de tous les animaux — 1 mètre ! Mais mangeait des plantes !',
    chasseurs: 'Tarbosaure — mais les griffes repoussaient !',
    proies: 'Mange des plantes',
    amis: 'Solitaire',
    fait: 'Il avait des griffes d\'1 mètre de long — les plus longues de tous les animaux ! Et pourtant il mangeait des feuilles et des plantes paisiblement !',
    desc: 'Le Therizinosaurus avait les griffes les plus longues de toute l\'histoire des animaux — 1 mètre chacune ! Mais malgré ces griffes impressionnantes, il ne mangeait que des plantes et des feuilles !',
    png: 'Therizinosaurus.png',
    color: '#117864',
  },
  {
    id: 'dimetrodon',
    name: 'Dimétrodon',
    full: 'Dimetrodon grandis',
    cat: 'airs_mers',
    epoque: 'Permien · il y a 280 millions d\'ans (avant les dinos !)',
    region: 'Amérique du Nord',
    taille_m: 3.5,
    poids_t: 0.25,
    comp_taille: 'aussi long qu\'une grande moto',
    comp_poids: 'aussi lourd qu\'un grand chien',
    regime: '🥩 Carnivore',
    superpower: 'Une grande voile pour se réchauffer au soleil — le thermomètre vivant !',
    chasseurs: 'Autres prédateurs du Permien',
    proies: 'Petits reptiles',
    amis: 'Solitaire',
    fait: 'Attention : le Dimétrodon N\'EST PAS un dinosaure ! Il vivait 50 millions d\'ans AVANT eux et est en fait plus proche de nous (les mammifères) que des dinos !',
    desc: 'Le Dimétrodon n\'est pas un dinosaure — c\'est un ancêtre des mammifères ! Il vivait bien avant les dinos. Sa grande voile sur le dos lui servait à se réchauffer au soleil.',
    png: 'Dimetrodon.png',
    color: '#0e6655',
  },
];
