"""Composition Papa Yann tile-picker 2026-05-11 - route plus LARGE (questionnement).

Layout 17x9. Papa Yann propose une route avec PLUSIEURS ROWS d'asphalte au lieu d'une.
A render pour voir si c'est plus realiste / plaisant que notre route_h actuel (5 rows seulement).
"""

ground = [
    ['roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png'],
    ['roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_23.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_47.png', None, None, None, None, None, None, 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_24.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png'],
    ['roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_19.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_29.png', None, 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_19.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_19.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_19.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_19.png', None, None, None, None, None, None, None, None, None, 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_19.png'],
    ['roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_16.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_30.png', None, 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_16.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', None, None, None, None, None, None, None, 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_21.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_21.png'],
    ['roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_2.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_30.png', None, 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_2.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_2.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_2.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_2.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_2.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_2.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_2.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_2.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_2.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_2.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_14.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_2.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_2.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_2.png'],
    ['roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_31.png', None, 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_19.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_16.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_16.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_16.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png'],
    ['roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_2.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_32.png', None, 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_2.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_2_46.png', None, None, None, None, 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_2_46.png', None, None, None, None, 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_2.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_2.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_2.png'],
    ['roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', None, None, None, None, None, None, None, None, None, None, 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png'],
    ['roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png'],
]

SNIPPET = {'name': 'papa_route_large', 'cols': 17, 'rows': 9, 'ground': ground, 'objects': []}
