"""REFERENCE CANONIQUE Papa Yann 2026-05-12 — CARREFOUR (croisement en croix) (14x13).

Export tile-picker brut. AUCUNE modification, AUCUNE interpretation.
Source unique de verite pour les carrefours MaxPlay.

Si re-utilise pour produire des macros / autres orientations, toute brique
DOIT etre extraite de ce fichier (par copie de cases), jamais inventee.
"""

ground = [
    ['roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_4.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_4.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_8.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png'],
    ['roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_6.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_6.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_6.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_6.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_6.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_6.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_5.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_4.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_7.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_19.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_19.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_19.png'],
    ['roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_20.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_20.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_22.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_15.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png'],
    ['roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_2.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_2.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_2.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_2.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_2.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_2.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_6.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_6.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_13.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_6.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_6.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_6.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_6.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_6.png'],
    ['roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_22.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_20.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_22.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_20.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_22.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_4.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png'],
    ['roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_2.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_2.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_2.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_2.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_2.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_2.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_2_3.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_20.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_4.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_1.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_2.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_2.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_2.png'],
    ['roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_2_4.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_4.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_8.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png'],
    [None, None, None, None, None, 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_4.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_4.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_8.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', None, None],
    [None, None, None, None, None, 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_4.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_20.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_4.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_8.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', None, None],
    [None, None, None, None, None, 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_4.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_22.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_4.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_8.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', None, None],
    [None, None, None, None, None, 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_4.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_4.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_8.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', None, None],
    [None, None, None, None, None, 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_4.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_20.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_4.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_8.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', None, None],
    [None, None, None, None, None, 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_4.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Asphalt_1_Variation_4.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_10.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_8.png', 'roads/ME_Singles_City_Terrains_48x48_Sidewalk_1_9.png', None, None],
]

SNIPPET = {'name': 'ref_papa_carrefour', 'cols': 14, 'rows': 13, 'ground': ground, 'objects': []}
