import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({viewport:{width:412,height:820}, deviceScaleFactor:2});
const errs=[]; p.on('pageerror',e=>errs.push(e.message));
await p.goto('file:///C:/ProjetsPerso/Claude_Projects/MaxPlay/site/index.html',{waitUntil:'networkidle'});
await p.waitForTimeout(800);
console.log('badge présent:', await p.locator('#av-badge').count());
await p.screenshot({path:'C:/tmp/picker_1_initial.png'});
await p.click('#av-badge'); await p.waitForTimeout(400);
console.log('modale ouverte:', await p.locator('#av-ov.show').count(), '· cellules:', await p.locator('.av-cell').count());
await p.screenshot({path:'C:/tmp/picker_2_modal.png'});
await p.click('.av-cell[data-id="trex"]'); await p.waitForTimeout(600);
const stored = await p.evaluate(()=>localStorage.getItem('maxplay_avatar'));
const hasImg = await p.locator('#av-badge img').count();
console.log('choix stocké:', stored, '· badge a une image:', hasImg);
await p.reload({waitUntil:'networkidle'}); await p.waitForTimeout(600);
const persist = await p.evaluate(()=>localStorage.getItem('maxplay_avatar'));
const hasImg2 = await p.locator('#av-badge img').count();
console.log('après reload — stocké:', persist, '· badge image:', hasImg2);
await p.screenshot({path:'C:/tmp/picker_3_chosen.png'});
console.log('erreurs JS:', errs.length?JSON.stringify(errs.slice(0,4)):'aucune');
await b.close();
